force-app/main/default/objects/Case/fields/Beneficiary__c.field-meta.xml
<CustomField>
    <fullName>Beneficiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beneficiary</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Connections__c/Connections__c.object-meta.xml
<CustomObject>
    <label>Connection</label>
    <nameField>
        <label>Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Connections__c/fields/Is_Statement_Recipient__c.field-meta.xml
<CustomField>
    <fullName>Is_Statement_Recipient__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Statement Recipient</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Connections__c/fields/Relationship_Types__c.field-meta.xml
<CustomField>
    <fullName>Relationship_Types__c</fullName>
    <label>Relationship Types</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Case Manager</fullName>
            </value>
            <value>
                <fullName>Co-Guardian</fullName>
            </value>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Guardian</fullName>
            </value>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Rep. Payee</fullName>
            </value>
            <value>
                <fullName>Sibling</fullName>
            </value>
            <value>
                <fullName>Sister</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Connections__c/fields/True_Link_Id__c.field-meta.xml
<CustomField>
    <fullName>True_Link_Id__c</fullName>
    <externalId>true</externalId>
    <label>True Link ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Connections__c/fields/Trust__c.field-meta.xml
<CustomField>
    <fullName>Trust__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trust</label>
    <referenceTo>Trust__c</referenceTo>
    <relationshipLabel>Connections</relationshipLabel>
    <relationshipName>Connections</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Beneficiary.recordType-meta.xml
<RecordType>
    <fullName>Beneficiary</fullName>
    <active>true</active>
    <label>Beneficiary</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Pooled_Trust__c/Pooled_Trust__c.object-meta.xml
<CustomObject>
    <label>Pooled Trust</label>
    <nameField>
        <label>Pooled Trust Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pooled Trusts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pooled_Trust__c/fields/Trust_ID__c.field-meta.xml
<CustomField>
    <fullName>Trust_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Trust ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/TruelinkData__c/TruelinkData__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Truelink Data</label>
</CustomObject>

force-app/main/default/objects/TruelinkData__c/fields/Sandbox_Apikey__c.field-meta.xml
<CustomField>
    <fullName>Sandbox_Apikey__c</fullName>
    <label>Sandbox Apikey</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/TruelinkData__c/fields/Sandbox_Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Sandbox_Endpoint__c</fullName>
    <label>Sandbox Endpoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trust__c/Trust__c.object-meta.xml
<CustomObject>
    <description>Record the history of trust agreements for a beneficiary</description>
    <label>Trust</label>
    <nameField>
        <label>Trust ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trusts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trust__c/fields/Beneficiary__c.field-meta.xml
<CustomField>
    <fullName>Beneficiary__c</fullName>
    <label>Beneficiary</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trusts</relationshipLabel>
    <relationshipName>Trusts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trust__c/fields/Pooled_Trust__c.field-meta.xml
<CustomField>
    <fullName>Pooled_Trust__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pooled Trust</label>
    <referenceTo>Pooled_Trust__c</referenceTo>
    <relationshipLabel>Trusts</relationshipLabel>
    <relationshipName>Trusts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trust__c/fields/TrueLink_ID__c.field-meta.xml
<CustomField>
    <fullName>TrueLink_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>TrueLink ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Trust__c/fields/Trust_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Trust_Portfolio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trust Portfolio</label>
    <referenceTo>Trust_Portfolio__c</referenceTo>
    <relationshipLabel>Trusts</relationshipLabel>
    <relationshipName>Trusts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trust_Portfolio__c/Trust_Portfolio__c.object-meta.xml
<CustomObject>
    <label>Trust Portfolio</label>
    <nameField>
        <label>Trust Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trust Portfolios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trust_Portfolio__c/fields/Pooled_Trust__c.field-meta.xml
<CustomField>
    <fullName>Pooled_Trust__c</fullName>
    <label>Pooled Trust</label>
    <referenceTo>Pooled_Trust__c</referenceTo>
    <relationshipLabel>Trust Portfolios</relationshipLabel>
    <relationshipName>Trust_Portfolios</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trust_Portfolio__c/fields/True_Link_Portfolio_ID__c.field-meta.xml
<CustomField>
    <fullName>True_Link_Portfolio_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>TrueLink Portfolio ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Trust_Portfolio__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Portfolio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TrueLinkConnectionsSyncBatchTest.cls
@isTest
public class TrueLinkConnectionsSyncBatchTest {

    @TestSetup
    static void setup() {
        TruelinkData__c setting = new TruelinkData__c();
        setting.ApiKey__c = 'Apikey test';
        setting.Endpoint__c = 'https://test.truelinkfinancial.com/api/v2';
        setting.Sandbox_Apikey__c = 'Apikey test';
        setting.Sandbox_Endpoint__c = 'https://test.truelinkfinancial.com/api/v2';
        insert setting;
    }

    @isTest
    static void testBatchExecute() {
        Test.setMock(HttpCalloutMock.class, new ConnectionsMock());

        Contact con = new Contact(LastName = 'Test Beneficiary');
        insert con;

        Pooled_Trust__c pc = new Pooled_Trust__c(Trust_Id__c = 'TEST123');
        insert pc;

        Trust_Portfolio__c tp = new Trust_Portfolio__c(
            Name = 'Test Portfolio',
            Is_Default__c = true,
            True_Link_Portfolio_ID__c = 'test-portfolio',
            Type__c = 'Portfolio',
            Pooled_Trust__c = pc.Id
        );
        insert tp;

        Trust__c trust = new Trust__c(
            Name = 'Test Trust',
            Beneficiary__c = con.Id,
            Trust_Portfolio__c = tp.Id,
            Pooled_Trust__c = pc.Id,
            TrueLink_ID__c = 'aaron-streufert-x2364041'
        );
        insert trust;

        Test.startTest();
        Database.executeBatch(new TrueLinkConnectionsSyncBatch(), 1);
        Test.stopTest();

        List<Connections__c> connections = [
            SELECT Id, True_Link_Id__c, First_Name__c, Last_Name__c,
                   Trust__c, Relationship_Types__c, Is_Statement_Recipient__c
            FROM Connections__c
        ];
        System.assertEquals(7, connections.size(), 'Expected 7 connection records');
        System.assertEquals(trust.Id, connections[0].Trust__c, 'Connection should be linked to Trust');
    }

    private class ConnectionsMock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(200);
            res.setHeader('Content-Type', 'application/json');
            res.setBody(
                '{"data":[' +
                    '{"type":"connection","id":"19471","attributes":{"firstName":"Jessica","lastName":"Dalton","mobile":"9136340783","email":"jessicadalton@lifecentersofkansas.com","companyName":null,"notes":"Relationship: Rep. payee","isCommon":false,"street1":null,"street2":null,"city":null,"state":"","zip":""},"relationships":{"organization":{"data":{"type":"organization","id":"arcare-x1349406"}},"connectionRelationship":{"data":{"type":"connection_relationship","id":"21624"}}}},' +
                    '{"type":"connection","id":"19472","attributes":{"firstName":"Angela","lastName":"Pitts","mobile":"9134844207","email":"angiepitts1@comcast.net","companyName":null,"notes":"Relationship: Case mgr.","isCommon":false,"street1":null,"street2":null,"city":null,"state":"","zip":""},"relationships":{"organization":{"data":{"type":"organization","id":"arcare-x1349406"}},"connectionRelationship":{"data":{"type":"connection_relationship","id":"21625"}}}},' +
                    '{"type":"connection","id":"19473","attributes":{"firstName":"Sherry","lastName":"Streufert","mobile":"9133417454","email":"sherrystreufert@yahoo.com","companyName":null,"notes":"Relationship: mother/gdn","isCommon":false,"street1":"4404 W. 78th St.","street2":null,"city":"Prairie Village","state":"KS","zip":"66208"},"relationships":{"organization":{"data":{"type":"organization","id":"arcare-x1349406"}},"connectionRelationship":{"data":{"type":"connection_relationship","id":"21626"}}}},' +
                    '{"type":"connection","id":"19474","attributes":{"firstName":"Sherry","lastName":"Streufert","mobile":"9135449716","email":"sherrystreufert@yahoo.com","companyName":null,"notes":"Relationship: Mother/gdn","isCommon":false,"street1":"4404 W 78th St","street2":null,"city":"Prairie Village","state":"KS","zip":"66208"},"relationships":{"organization":{"data":{"type":"organization","id":"arcare-x1349406"}},"connectionRelationship":{"data":{"type":"connection_relationship","id":"21627"}}}},' +
                    '{"type":"connection","id":"19475","attributes":{"firstName":"Stephen","lastName":"Streufert","mobile":null,"email":null,"companyName":null,"notes":"Relationship: father","isCommon":false,"street1":"3313-3 Red Bridge Rd","street2":null,"city":"Kansas City","state":"MO","zip":"64137"},"relationships":{"organization":{"data":{"type":"organization","id":"arcare-x1349406"}},"connectionRelationship":{"data":{"type":"connection_relationship","id":"21628"}}}},' +
                    '{"type":"connection","id":"27748","attributes":{"firstName":"Amber","lastName":"Hastings","mobile":"9139635229","email":"ahastings37@yahoo.com","companyName":"","notes":"co-guardian","isCommon":false,"street1":"813 Colbern St","street2":"","city":"Belton","state":"MO","zip":"64012"},"relationships":{"organization":{"data":{"type":"organization","id":"arcare-x1349406"}},"connectionRelationship":{"data":{"type":"connection_relationship","id":"30185"}}}},' +
                    '{"type":"connection","id":"39329","attributes":{"firstName":"Aaron Streufert","lastName":null,"mobile":null,"email":null,"companyName":null,"notes":null,"isCommon":false,"street1":"c/o Sherry Streufert","street2":"4404 W. 78th St.","city":"Prairie Village","state":"KS","zip":"66208"},"relationships":{"organization":{"data":{"type":"organization","id":"arcare-x1349406"}},"connectionRelationship":{"data":{"type":"connection_relationship","id":"42112"}}}}' +
                '],"included":[' +
                    '{"type":"connection_relationship","id":"21624","attributes":{"relationshipTypes":[],"isStatementRecipient":false}},' +
                    '{"type":"connection_relationship","id":"21625","attributes":{"relationshipTypes":[],"isStatementRecipient":false}},' +
                    '{"type":"connection_relationship","id":"21626","attributes":{"relationshipTypes":[],"isStatementRecipient":false}},' +
                    '{"type":"connection_relationship","id":"21627","attributes":{"relationshipTypes":[],"isStatementRecipient":false}},' +
                    '{"type":"connection_relationship","id":"21628","attributes":{"relationshipTypes":[],"isStatementRecipient":false}},' +
                    '{"type":"connection_relationship","id":"30185","attributes":{"relationshipTypes":["Guardian","Sister"],"isStatementRecipient":false}},' +
                    '{"type":"connection_relationship","id":"42112","attributes":{"relationshipTypes":[],"isStatementRecipient":true}}' +
                ']}'
            );
            return res;
        }
    }
}