force-app/main/default/objects/Bulk_Custom_Email_Template__c/Bulk_Custom_Email_Template__c.object-meta.xml
<CustomObject>
    <label>Bulk Custom Email Template</label>
    <nameField>
        <label>Bulk Custom Email Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bulk Custom Email Templates</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Bulk_Custom_Email_Template__c/fields/Custom_Email_Template__c.field-meta.xml
<CustomField>
    <fullName>Custom_Email_Template__c</fullName>
    <label>Custom Email Template</label>
    <referenceTo>Custom_Email_Template__c</referenceTo>
    <relationshipLabel>Bulk Custom Email Templates</relationshipLabel>
    <relationshipName>Bulk_Custom_Email_Templates</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Bulk_Custom_Email_Template__c/fields/Final_Email_Body__c.field-meta.xml
<CustomField>
    <fullName>Final_Email_Body__c</fullName>
    <label>Final Email Body</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Custom_Email_Template__c/Custom_Email_Template__c.object-meta.xml
<CustomObject>
    <label>Custom Email Template</label>
    <nameField>
        <label>Custom Email Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Email Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/pdfPageControllerBulk.cls
public with sharing class pdfPageControllerBulk {
    public List<String> pdfText { get; set; }

    public pdfPageControllerBulk() {
        initialize();
    }

    public pdfPageControllerBulk(ApexPages.StandardController con) {
        initialize();
    }

    private void initialize() {
        pdfText = new List<String>();
        String recId = ApexPages.currentPage()?.getParameters()?.get('recId');
        
        if (String.isNotEmpty(recId)) {
            Id currentUserId = UserInfo.getUserId();
            for (Bulk_Custom_Email_Template__c bcet : [SELECT Final_Email_Body__c 
                FROM Bulk_Custom_Email_Template__c 
                WHERE Custom_Email_Template__c = :recId AND CreatedById =: currentUserId]) {
                pdfText.add(bcet.Final_Email_Body__c);
            }
        }
    }
}