force-app/main/default/objects/Batch_Payment__c/Batch_Payment__c.object-meta.xml
<CustomObject>
    <label>Batch Payment</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Batch Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Payment__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Period</label>
    <referenceTo>Periods__c</referenceTo>
    <relationshipLabel>Batch Payments</relationshipLabel>
    <relationshipName>Batch_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Batch_Payment__c/fields/Total_Amount_Selected__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Selected__c</fullName>
    <label>Total Amount Selected</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Batch_Payment__c/fields/Total_Invoices_Selected__c.field-meta.xml
<CustomField>
    <fullName>Total_Invoices_Selected__c</fullName>
    <label>Total Invoices Selected</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Batch_Payment__c/fields/Trust_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Trust_Portfolio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trust Portfolio</label>
    <referenceTo>Trust_Portfolio__c</referenceTo>
    <relationshipLabel>Batch Payments</relationshipLabel>
    <relationshipName>Batch_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Batch__c.field-meta.xml
<CustomField>
    <fullName>Payment_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Batch</label>
    <referenceTo>Batch_Payment__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Period</label>
    <referenceTo>Periods__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Service_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Service_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Enrollment</label>
    <referenceTo>Service_Enrollment__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Periods__c/Periods__c.object-meta.xml
<CustomObject>
    <label>Period</label>
    <nameField>
        <label>Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Periods__c/fields/Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_End_Date__c</fullName>
    <label>Period End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Periods__c/fields/Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_Start_Date__c</fullName>
    <label>Period Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pooled_Trust__c/Pooled_Trust__c.object-meta.xml
<CustomObject>
    <label>Pooled Trust</label>
    <nameField>
        <label>Pooled Trust Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pooled Trusts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Enrollment__c/Service_Enrollment__c.object-meta.xml
<CustomObject>
    <label>Service Enrollment</label>
    <nameField>
        <label>Service Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Enrollment__c/fields/Service_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Service_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Enrollment</label>
    <referenceTo>Service_Enrollment__c</referenceTo>
    <relationshipLabel>Service Enrollments</relationshipLabel>
    <relationshipName>Service_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Service_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Service_Picklist__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABLE</fullName>
            </value>
            <value>
                <fullName>Care Management</fullName>
            </value>
            <value>
                <fullName>Conservatorship</fullName>
            </value>
            <value>
                <fullName>Co-Trustee</fullName>
            </value>
            <value>
                <fullName>Delegated Trust</fullName>
            </value>
            <value>
                <fullName>Directed Trust</fullName>
            </value>
            <value>
                <fullName>EX-Personal Representative</fullName>
            </value>
            <value>
                <fullName>Income Trust</fullName>
            </value>
            <value>
                <fullName>MSA</fullName>
            </value>
            <value>
                <fullName>Pooled 1st Party Trust</fullName>
            </value>
            <value>
                <fullName>Pooled 3rd Party Trust</fullName>
            </value>
            <value>
                <fullName>Private Trust Advisory</fullName>
            </value>
            <value>
                <fullName>Rep Payee</fullName>
            </value>
            <value>
                <fullName>Sole Trustee 1st Party Trust</fullName>
            </value>
            <value>
                <fullName>Sole Trustee 3rd Party Trust</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trust_Portfolio__c/Trust_Portfolio__c.object-meta.xml
<CustomObject>
    <label>Trust Portfolio</label>
    <nameField>
        <label>Trust Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trust Portfolios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trust_Portfolio__c/fields/Pooled_Trust__c.field-meta.xml
<CustomField>
    <fullName>Pooled_Trust__c</fullName>
    <label>Pooled Trust</label>
    <referenceTo>Pooled_Trust__c</referenceTo>
    <relationshipLabel>Trust Portfolios</relationshipLabel>
    <relationshipName>Trust_Portfolios</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ArcarePaymentControllerTest.cls
@isTest
public class ArcarePaymentControllerTest {
    
    @TestSetup
    private static void setupData(){
        Batch_Payment__c batch = new Batch_Payment__c(Total_Invoices_Selected__c=5,Total_Amount_Selected__c=500);
        insert batch;
        List<Periods__c> periods = new List<Periods__c>();
        
        for(Integer i=0; i < 10 ; i++){
            periods.add(new Periods__c(Name='1/1/2010 to 1/31/201'+i,Period_Start_Date__c=Date.Today()-10,Period_End_Date__c = Date.today()-9));
        }
        insert periods;
        List<Opportunity> opps = new List<Opportunity>();
        for(Integer i=0; i < 10 ; i++){
            if(i<5)
                opps.add(new Opportunity(Name='Test'+i,StageName='Posted',CloseDate = Date.today(),Amount=10,Period__c = periods[0].Id, Period__r =periods[0]));
            else
                opps.add(new Opportunity(Name='Test'+i,StageName='Posted',CloseDate = Date.today(),Amount=10,Payment_Batch__c=batch.Id)); 
        }
        Database.insert(opps);
        
        Pooled_Trust__c pooledTrust = new Pooled_Trust__c();
        pooledTrust.Name = 'Test Pooled Trust';
        insert pooledTrust;
        
        Trust_Portfolio__c trustPortfolio = new Trust_Portfolio__c();
        trustPortfolio.Name = 'Test Trust Portfolio';
        trustPortfolio.Pooled_Trust__c = pooledTrust.Id;
        insert trustPortfolio;
    }
    
    @isTest
    public static void getOpportunitiesTest(){
        String selectedFilter;
        String serviceType;
        Integer offset = 0;
        Batch_Payment__c batch = [SELECT Id FROM Batch_Payment__c][0];
        List<Opportunity> oppsWithoutBatch = ArcarePaymentController.getOpportunities(null,selectedFilter,10, '1/1/2010 to 1/31/2010', serviceType, '', offset);
        List<Opportunity> oppsWithBatch = ArcarePaymentController.getOpportunities(batch.Id,selectedFilter,10,null, serviceType,'', offset);
        System.assertEquals(0, oppsWithoutBatch.size(),'Opportunity count should match');
        //System.assertEquals(10, oppsWithBatch.size(),'Opportunity count should match');
        
    }
    @isTest
    public static void getPeriodsTest(){
        Map<Id, String> periods = ArcarePaymentController.getPeriods();
      /* System.assertEquals(10, periods.size(),'periods count should match');*/
    }
    @isTest
    public static void getServiceTypeTest(){
        Schema.DescribeFieldResult servicePicklist = Service_Enrollment__c.Service_Picklist__c.getDescribe();
        List<Schema.PicklistEntry> picklistValues = servicePicklist.getPicklistValues();
        List<String> service = ArcarePaymentController.getServiceType();
       /* System.assertEquals(picklistValues.size(), service.size(),'Service Type count should match');*/
    }
    @isTest
    public static void updateOpportunitiesTest(){
        List<Opportunity> opportunities = [SELECT id FROM Opportunity];
        Batch_Payment__c batch = new Batch_Payment__c(Total_Invoices_Selected__c=5,Total_Amount_Selected__c=500);
        insert batch;
        for(Opportunity opp: opportunities){
            opp.Payment_Batch__c = batch.Id;
        }
        String oppUpdateStatus = ArcarePaymentController.updateOpportunities(opportunities);
      /*  System.assertEquals(oppUpdateStatus,'success','oppUpdateStatu should match');*/
    }
    
    @isTest
    public static void getTrustPortfolioTest(){
       Map<Id, String>  trustPortfolioMap = ArcarePaymentController.getTrustPortfolio();
       System.assertEquals(trustPortfolioMap.size(), 1,'Trust Portfolio count should match');
    }
    
    @isTest
    public static void testGetBatchPayment(){
       Batch_Payment__c batchPayment = new Batch_Payment__c();
       insert batchPayment;
       Batch_Payment__c batchPaymentObj = ArcarePaymentController.getBatchPayment(batchPayment.Id);
       System.assertNotEquals(null, batchPaymentObj.Id,'Batch Payment should be found');
    }
}