force-app/main/default/objects/Batch_Payment__c/Batch_Payment__c.object-meta.xml
<CustomObject>
    <label>Batch Payment</label>
    <nameField>
        <displayFormat>BP-{0000}</displayFormat>
        <label>Batch Payment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Batch Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Batch_Payment__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Period</label>
    <referenceTo>Periods__c</referenceTo>
    <relationshipLabel>Batch Payments</relationshipLabel>
    <relationshipName>Batch_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Batch_Payment__c/fields/Trust_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Trust_Portfolio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trust Portfolio</label>
    <referenceTo>Trust_Portfolio__c</referenceTo>
    <relationshipLabel>Batch Payments</relationshipLabel>
    <relationshipName>Batch_Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Bill_Date__c.field-meta.xml
<CustomField>
    <fullName>Bill_Date__c</fullName>
    <label>Bill Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Integration_Status__c.field-meta.xml
<CustomField>
    <fullName>Integration_Status__c</fullName>
    <label>Integration Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Ready To Sync</fullName>
            </value>
            <value>
                <fullName>Synced</fullName>
            </value>
            <value>
                <fullName>Sync Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Batch__c.field-meta.xml
<CustomField>
    <fullName>Payment_Batch__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Payment Batch</label>
    <referenceTo>Batch_Payment__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Period</label>
    <referenceTo>Periods__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Service_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Service_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Enrollment</label>
    <referenceTo>Service_Enrollment__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Periods__c/Periods__c.object-meta.xml
<CustomObject>
    <label>Period</label>
    <nameField>
        <label>Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Periods__c/fields/Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_Start_Date__c</fullName>
    <label>Period Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/Service_Enrollment__c.object-meta.xml
<CustomObject>
    <label>Service Enrollment</label>
    <nameField>
        <label>Service Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Enrollment__c/fields/Service_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Service_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Enrollment</label>
    <referenceTo>Service_Enrollment__c</referenceTo>
    <relationshipLabel>Service Enrollments</relationshipLabel>
    <relationshipName>Service_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Service_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Service_Picklist__c</fullName>
    <label>Service</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ABLE</fullName>
            </value>
            <value>
                <fullName>Care Management</fullName>
            </value>
            <value>
                <fullName>Conservatorship</fullName>
            </value>
            <value>
                <fullName>Co-Trustee</fullName>
            </value>
            <value>
                <fullName>Delegated Trust</fullName>
            </value>
            <value>
                <fullName>Directed Trust</fullName>
            </value>
            <value>
                <fullName>EX-Personal Representative</fullName>
            </value>
            <value>
                <fullName>Income Trust</fullName>
            </value>
            <value>
                <fullName>MSA</fullName>
            </value>
            <value>
                <fullName>Pooled 1st Party Trust</fullName>
            </value>
            <value>
                <fullName>Pooled 3rd Party Trust</fullName>
            </value>
            <value>
                <fullName>Private Trust Advisory</fullName>
            </value>
            <value>
                <fullName>Rep Payee</fullName>
            </value>
            <value>
                <fullName>Sole Trustee 1st Party Trust</fullName>
            </value>
            <value>
                <fullName>Sole Trustee 3rd Party Trust</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trust_Portfolio__c/Trust_Portfolio__c.object-meta.xml
<CustomObject>
    <label>Trust Portfolio</label>
    <nameField>
        <label>Trust Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trust Portfolios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/ArcarePaymentController.cls
public class ArcarePaymentController {
    @AuraEnabled
    public static List<Opportunity> getOpportunities (Id batchId, String selectedFilter, Decimal filterAmount, String period, 
        String serviceType, String trustPortfolio, Integer offset){
        /*if(selectedFilter == 'Unselected'){
            batchId = null;
        }*/
        String query = 'Select ID, Name,Service_Enrollment__r.Name,Amount,Period__r.Name,Payment_Batch__c,CreatedDate,Bill_Date__c from Opportunity';
        if(selectedFilter == 'Unselected'){
            query += ' where Payment_Batch__c = null';
        } else if (selectedFilter == 'Selected') {
            query += ' where Payment_Batch__c = :batchId';
        }
        else{
            query += ' where (Payment_Batch__c = null or Payment_Batch__c = :batchId)';
        }
        if(filterAmount!=null){
            query += ' and Amount = :filterAmount';
        }
        if(!String.isBlank(period)){
            query += ' and Period__c = :period';
        }
        if(!String.isBlank(serviceType)){
            query += ' and Service_Enrollment__r.Service_Picklist__c = :serviceType';
        }
        if(!String.isBlank(trustPortfolio)){
            query += ' and Payment_Batch__r.Trust_Portfolio__c = :trustPortfolio';
        }
        //query += ' limit 20 offset :offset';
        query +=  ' and Integration_Status__c= \'Synced\' and stagename =\'Invoiced\''; //and iswon=false and isclosed=false
        //query += ' limit 20';    
        return Database.query(query);
    }
    @AuraEnabled
    public static String updateOpportunities (List<Opportunity>opportunities ){
         try {
            update opportunities;
            return 'success';
        }catch(DmlException e) {
            return 'server error';
        }        
    }

    @AuraEnabled
    public static Map<Id, String> getPeriods(){
        Map<Id, String> mapOfPeriodsName = new Map<Id, String>();
       List<Periods__c> periods = [select Id, Name from Periods__c where Period_Start_Date__c = LAST_N_MONTHS:4];
       for(Periods__c period : periods){
            mapOfPeriodsName.put(period.Id, period.Name);
       }
       return mapOfPeriodsName;
    }

    @AuraEnabled
    public static List<String> getServiceType(){
        List<String> listOfServiceTypeValues = new List<String>();
        Schema.DescribeFieldResult servicePicklist = Service_Enrollment__c.Service_Picklist__c.getDescribe();
        List<Schema.PicklistEntry> picklistValues = servicePicklist.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : picklistValues){
            listOfServiceTypeValues.add(pickListVal.getValue());
        }
        return listOfServiceTypeValues;
    }
    @AuraEnabled
    public static Map<Id, String> getTrustPortfolio(){
        Map<Id, String> mapOfTrustPortfolio = new Map<Id, String>();
        List<Trust_Portfolio__c> listOfTrustPortfolio = [SELECT Id, Name FROM Trust_Portfolio__c];

        for(Trust_Portfolio__c trustPortfolio : listOfTrustPortfolio){
            mapOfTrustPortfolio.put(trustPortfolio.Id, trustPortfolio.Name);
        }
        return mapOfTrustPortfolio;
    }

    @AuraEnabled
    public static Batch_Payment__c getBatchPayment(Id recordId){
        Batch_Payment__c batchPaymentObj = [SELECT Id, Period__c, Trust_Portfolio__c, Service_Type__c FROM Batch_Payment__c WHERE Id =: recordId LIMIT 1];
        return batchPaymentObj;
    }
}