force-app/main/default/objects/Custom_Email_Template__c/Custom_Email_Template__c.object-meta.xml
<CustomObject>
    <label>Custom Email Template</label>
    <nameField>
        <label>Custom Email Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Email Templates</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Email_Template__c/fields/Final_Body__c.field-meta.xml
<CustomField>
    <fullName>Final_Body__c</fullName>
    <label>Final Body</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/pdfPageController.cls
public with sharing class pdfPageController {
    public String pdfText {get;set;}
    public pdfPageController() {
        String recId = String.escapeSingleQuotes(ApexPages.currentPage()?.getParameters()?.get('recId'));
        this.pdfText = [Select Id, Final_Body__c from Custom_Email_Template__c where Id=:recId]?.Final_Body__c;
    }
    public pdfPageController(ApexPages.StandardController con){
        String recId = String.escapeSingleQuotes(ApexPages.currentPage()?.getParameters()?.get('recId'));
        this.pdfText = [Select Id, Final_Body__c from Custom_Email_Template__c where Id=:recId]?.Final_Body__c;
    }
}