force-app/main/default/objects/Batch_Class_Configuration__mdt/Batch_Class_Configuration__mdt.object-meta.xml
<CustomObject>
    <label>Batch Class Configuration</label>
    <pluralLabel>Batch Class Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Batch_Class_Configuration__mdt/fields/Frequency_in_Days__c.field-meta.xml
<CustomField>
    <fullName>Frequency_in_Days__c</fullName>
    <label>Frequency in Days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Track_API_Call__c/Track_API_Call__c.object-meta.xml
<CustomObject>
    <label>Track API Call</label>
    <nameField>
        <displayFormat>API-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Track API Calls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CleanApiLogs.cls
public class CleanApiLogs implements Database.Batchable<sObject>,Schedulable {
    public Database.QueryLocator start(Database.BatchableContext bc){
        Batch_Class_Configuration__mdt setting;
        setting = [
            SELECT Frequency_in_Days__c
            FROM Batch_Class_Configuration__mdt 
            WHERE DeveloperName = 'CleanApiLogs'
            LIMIT 1
        ];
        Date myDateStart;
        if(Test.isRunningTest()){
            myDateStart = Date.today();
        } else {
            myDateStart = Date.today().addDays(-1*Integer.valueOf(setting.Frequency_in_Days__c));
        }

        return Database.getQueryLocator('SELECT Id FROM Track_API_Call__c WHERE DAY_ONLY(CreatedDate) <=:myDateStart');
    }

      public void execute(Database.BatchableContext BC, List<Track_API_Call__c> trackApiList){
        delete trackApiList;
    }

    //finish method
    public void finish(Database.BatchableContext BC){
        BatchUtils.rescheduleBatch('CleanApiLogs',new CleanApiLogs());
    }

    public void execute(SchedulableContext sc) {
        Database.executebatch(this,200);
    }

}