force-app/main/default/objects/Connections__c/Connections__c.object-meta.xml
<CustomObject>
    <label>Connection</label>
    <nameField>
        <label>Connection Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Connections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Connections__c/fields/Update_True_Link__c.field-meta.xml
<CustomField>
    <fullName>Update_True_Link__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Update True Link</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Track_API_Call__c/Track_API_Call__c.object-meta.xml
<CustomObject>
    <label>Track API Call</label>
    <nameField>
        <displayFormat>API-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Track API Calls</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Track_API_Call__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <label>Error Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Track_API_Call__c/fields/Parent_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Record_Id__c</fullName>
    <label>Parent Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateConnectionsBatch.cls
public class UpdateConnectionsBatch implements Database.Batchable<sObject>, Database.AllowsCallouts {

    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator([Select Id from Connections__c where Update_True_Link__c = true]);
    }

    public void execute(Database.BatchableContext ctx, List<Connections__c> records){
        for(Connections__c con : records){
            try{
                TrueLinkApiHandler.updateConnection(con.Id);
            } catch(Exception e){
                insert new Track_API_Call__c(
                    Parent_Record_Id__c = con.Id,
                    Status__c = 'Error',
                    Error_Message__c = 'Error While Updating Connection. => ' + e.getMessage() + '=>' + e.getStackTraceString()
                );
            }
        }
    }

    public void finish(Database.BatchableContext ctx){
    }
}