force-app/main/default/objects/Closing__c/Closing__c.object-meta.xml
<CustomObject>
    <description>This tracks the closing process to completion</description>
    <label>Closing</label>
    <nameField>
        <label>Closing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Closings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Closing__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Not Active</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Remainder_Person__c/Remainder_Person__c.object-meta.xml
<CustomObject>
    <label>Remainder Person</label>
    <nameField>
        <label>Remainder Person Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Remainder Persons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Remainder_Person__c/fields/Closing__c.field-meta.xml
<CustomField>
    <fullName>Closing__c</fullName>
    <label>Closing</label>
    <referenceTo>Closing__c</referenceTo>
    <relationshipName>Remainderpersons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Remainder_Person__c/fields/Percent_of_Remaining_Funds__c.field-meta.xml
<CustomField>
    <fullName>Percent_of_Remaining_Funds__c</fullName>
    <label>% of Remaining Funds</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Remainder_Person__c/fields/Remainder_Person_Address__c.field-meta.xml
<CustomField>
    <fullName>Remainder_Person_Address__c</fullName>
    <formula>Remainder_Person_Contact__r.MailingStreet&amp;BR()
&amp;Remainder_Person_Contact__r.MailingCity&amp;&quot;, &quot;&amp;Remainder_Person_Contact__r.MailingState&amp;&quot; &quot;&amp;Remainder_Person_Contact__r.MailingPostalCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remainder Person Address</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Remainder_Person__c/fields/Remainder_Person_Contact__c.field-meta.xml
<CustomField>
    <fullName>Remainder_Person_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>This should link to the Remainderperson&apos;s Contact record, not the Beneficiary&apos;s Contact record</inlineHelpText>
    <label>Remainder Person Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Remainder Persons</relationshipLabel>
    <relationshipName>Remainderpersons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remainder_Person__c/fields/Remainder_Person_Email__c.field-meta.xml
<CustomField>
    <fullName>Remainder_Person_Email__c</fullName>
    <formula>Remainder_Person_Contact__r.Email</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remainder Person Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Remainder_Person__c/fields/Remainder_Person_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Remainder_Person_First_Name__c</fullName>
    <formula>Remainder_Person_Contact__r.FirstName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remainder Person First Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Remainder_Person__c/fields/Remainder_Person_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Remainder_Person_Last_Name__c</fullName>
    <formula>Remainder_Person_Contact__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remainder Person Last Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Remainder_Person__c/fields/Remainder_Person_Phone__c.field-meta.xml
<CustomField>
    <fullName>Remainder_Person_Phone__c</fullName>
    <formula>Remainder_Person_Contact__r.Phone</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Remainder Person Phone</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Remainder_Person__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>&quot;Active&quot;</defaultValue>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Deceased</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Unable to Locate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/remainderPersonTableController.cls
public without sharing class remainderPersonTableController {

    @AuraEnabled
    public static List<Remainder_Person__c> getRemainderPeople(
        Id closingId,
        Long ts,
        String filterLogic
    ) {
        if (closingId == null) {
            return new List<Remainder_Person__c>();
        }

        String q =
            'SELECT Id, Closing__c, Remainder_Person_Contact__c, Remainder_Person_Address__c, ' +
            'Remainder_Person_First_Name__c, Remainder_Person_Last_Name__c, ' +
            'Remainder_Person_Phone__c, Remainder_Person_Email__c, ' +
            'Percent_of_Remaining_Funds__c, Status__c ' +
            'FROM Remainder_Person__c ' +
            'WHERE Closing__c = :closingId';


        if (String.isNotBlank(filterLogic)) {
            q += ' AND ' + filterLogic;
        }

        q += ' ORDER BY CreatedDate ASC';
        return Database.query(q);
    }

    @AuraEnabled
    public static Remainder_Person__c saveRemainderPerson(Remainder_Person__c rp) {
        if (rp == null) {
            throw new AuraHandledException('Remainder Person record cannot be null');
        }
        upsert rp;
        return rp;
    }
}