force-app/main/default/objects/Trust__c/Trust__c.object-meta.xml
<CustomObject>
    <description>Record the history of trust agreements for a beneficiary</description>
    <label>Trust</label>
    <nameField>
        <label>Trust ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trusts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trust__c/fields/True_Link_Balance__c.field-meta.xml
<CustomField>
    <fullName>True_Link_Balance__c</fullName>
    <label>TrueLink Balance</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trust__c/fields/TrueLink_ID__c.field-meta.xml
<CustomField>
    <fullName>TrueLink_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>TrueLink ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Trust__c/fields/Trust_Status__c.field-meta.xml
<CustomField>
    <fullName>Trust_Status__c</fullName>
    <label>Trust Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intake</fullName>
                <default>true</default>
                <label>Intake</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Future Funded</fullName>
            </value>
            <value>
                <fullName>Closing</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active-Pending</fullName>
                <isActive>false</isActive>
                <label>Active-Pending</label>
            </value>
            <value>
                <fullName>Closing requested</fullName>
                <isActive>false</isActive>
                <label>Closing requested</label>
            </value>
            <value>
                <fullName>Materials Received-Complete</fullName>
                <isActive>false</isActive>
                <label>Materials Received-Complete</label>
            </value>
            <value>
                <fullName>Pending-Active</fullName>
                <isActive>false</isActive>
                <label>Pending-Active</label>
            </value>
            <value>
                <fullName>Pending-Inactive</fullName>
                <isActive>false</isActive>
                <label>Pending-Inactive</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
            <value>
                <fullName>Returning</fullName>
                <isActive>false</isActive>
                <label>Returning</label>
            </value>
            <value>
                <fullName>Reviewed</fullName>
                <isActive>false</isActive>
                <label>Reviewed</label>
            </value>
            <value>
                <fullName>Waiting/Hold</fullName>
                <isActive>false</isActive>
                <label>Waiting/Hold</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateBeneficiaryBalanceBatch.cls
public class UpdateBeneficiaryBalanceBatch implements Database.Batchable<sObject>,Schedulable,Database.AllowsCallouts {
    public Database.QueryLocator start(Database.BatchableContext bc){
        List<String> eligibleStatuses = new List<String>(TrueLinkApiHandler.getEligibleTrustStatuses());
        return Database.getQueryLocator([Select Id,TrueLink_ID__c,True_Link_Balance__c from trust__c where TrueLink_ID__c!=null and Trust_Status__c IN :eligibleStatuses]);
    }

    public void execute(Database.BatchableContext ctx,List<trust__c> records){   
        List<trust__c> newRecords = new List<trust__c>();
        for(trust__c trust:records){
            TrueLinkApiHandler.updateAccountBalance(trust.Id);
        }
    }

    public void finish(Database.BatchableContext ctx){
		Database.executeBatch(new UpdateDepositsBatch(),1); 
        if(!Test.isRunningTest()){
            BatchUtils.rescheduleBatch('UpdateBeneficiaryBalanceBatch',new UpdateBeneficiaryBalanceBatch());
    }
    } 

    public void execute(SchedulableContext  sc){
        Database.executeBatch(this,1);
    }
}