force-app/main/default/objects/Opportunity/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Service_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Service_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Enrollment</label>
    <referenceTo>Service_Enrollment__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type__c</fullName>
    <label>Charge Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CREDIT</fullName>
            </value>
            <value>
                <fullName>DIRECT EXPENSE</fullName>
            </value>
            <value>
                <fullName>HOURLY SERVICE</fullName>
            </value>
            <value>
                <fullName>FEES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/Service_Enrollment__c.object-meta.xml
<CustomObject>
    <label>Service Enrollment</label>
    <nameField>
        <label>Service Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Enrollment__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Billing_Attention_To__c.field-meta.xml
<CustomField>
    <fullName>Billing_Attention_To__c</fullName>
    <label>Billing Attention To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Billing_City__c.field-meta.xml
<CustomField>
    <fullName>Billing_City__c</fullName>
    <label>Billing City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Billing_State__c.field-meta.xml
<CustomField>
    <fullName>Billing_State__c</fullName>
    <label>Billing State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States_Abreviations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Billing_Street_1__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street_1__c</fullName>
    <label>Billing Street 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Billing_Street_2__c.field-meta.xml
<CustomField>
    <fullName>Billing_Street_2__c</fullName>
    <label>Billing Street 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Billing_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Billing_Zip_Code__c</fullName>
    <label>Billing Zip Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Copy1_Attention_To__c.field-meta.xml
<CustomField>
    <fullName>Copy1_Attention_To__c</fullName>
    <label>Copy1  Attention To</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Copy1_City__c.field-meta.xml
<CustomField>
    <fullName>Copy1_City__c</fullName>
    <label>Copy1 City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Copy1_State__c.field-meta.xml
<CustomField>
    <fullName>Copy1_State__c</fullName>
    <label>Copy1 State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States_Abreviations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Copy1_Street_1__c.field-meta.xml
<CustomField>
    <fullName>Copy1_Street_1__c</fullName>
    <label>Copy1 Street 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Copy1_Street_2__c.field-meta.xml
<CustomField>
    <fullName>Copy1_Street_2__c</fullName>
    <label>Copy1 Street 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Copy1_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Copy1_Zip_Code__c</fullName>
    <label>Copy1 Zip Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Copy2_Attention_To__c.field-meta.xml
<CustomField>
    <fullName>Copy2_Attention_To__c</fullName>
    <label>Copy2  Attention To</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Copy2_City__c.field-meta.xml
<CustomField>
    <fullName>Copy2_City__c</fullName>
    <label>Copy2 City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Copy2_State__c.field-meta.xml
<CustomField>
    <fullName>Copy2_State__c</fullName>
    <label>Copy2 State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States_Abreviations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Copy2_Street_1__c.field-meta.xml
<CustomField>
    <fullName>Copy2_Street_1__c</fullName>
    <label>Copy2 Street 1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Copy2_Street_2__c.field-meta.xml
<CustomField>
    <fullName>Copy2_Street_2__c</fullName>
    <label>Copy2 Street 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Copy2_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Copy2_Zip_Code__c</fullName>
    <label>Copy2 Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Mail_To_Attention__c.field-meta.xml
<CustomField>
    <fullName>Mail_To_Attention__c</fullName>
    <label>Mail To Attention</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Mail_To_City__c.field-meta.xml
<CustomField>
    <fullName>Mail_To_City__c</fullName>
    <label>Mail To City</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Mail_To_State__c.field-meta.xml
<CustomField>
    <fullName>Mail_To_State__c</fullName>
    <label>Mail To State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States_Abreviations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Mail_To_Street_1__c.field-meta.xml
<CustomField>
    <fullName>Mail_To_Street_1__c</fullName>
    <label>Mail To Street 1</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Mail_To_Street_2__c.field-meta.xml
<CustomField>
    <fullName>Mail_To_Street_2__c</fullName>
    <label>Mail To Street 2</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Mail_To_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Mail_To_Zip_Code__c</fullName>
    <label>Mail To Zip Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Service_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Service_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Enrollment</label>
    <referenceTo>Service_Enrollment__c</referenceTo>
    <relationshipLabel>Service Enrollments</relationshipLabel>
    <relationshipName>Service_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/States_Abreviations.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>NV</fullName>
    </customValue>
    <customValue>
        <fullName>NH</fullName>
    </customValue>
    <masterLabel>States Abreviations</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/InvoiceTemplateCombinedController.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 09-04-2024
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public without sharing class InvoiceTemplateCombinedController{
   
    public List<Opportunity> opportunities{get;set;}

    public InvoiceTemplateCombinedController(){
        String OpportunitiesIDs = ApexPages.CurrentPage().getParameters().get('id');
        List<String> opportunityList = OpportunitiesIDs.split(';');
        List<Opportunity> opportunityLists = new List<Opportunity>();

        for(Opportunity op : [SELECT Id,
            Service_Enrollment__r.Billing_Attention_To__c,
            Service_Enrollment__r.Billing_Street_1__c,
            Service_Enrollment__r.Billing_Street_2__c,
            Service_Enrollment__r.Billing_City__c,
            Service_Enrollment__r.Billing_State__c,
            Service_Enrollment__r.Billing_Zip_Code__c,
            Service_Enrollment__r.Name,
            Service_enrollment__r.Account_Number__c,
            CloseDate,
            Invoice_Number__c,
            Service_Enrollment__r.Mail_To_Attention__c,
            Service_Enrollment__r.Mail_To_Street_1__c,
            Service_Enrollment__r.Mail_To_Street_2__c,
            Service_Enrollment__r.Mail_To_City__c,
            Service_Enrollment__r.Mail_To_State__c,
            Service_Enrollment__r.Mail_To_Zip_Code__c,
            Service_Enrollment__r.Copy1_Attention_To__c,
            Service_Enrollment__r.Copy1_Street_1__c,
            Service_Enrollment__r.Copy1_Street_2__c,
            Service_Enrollment__r.Copy1_City__c,
            Service_Enrollment__r.Copy1_State__c,
            Service_Enrollment__r.Copy1_Zip_Code__c,
            Service_Enrollment__r.Copy2_Attention_To__c,Service_Enrollment__r.Copy2_Street_1__c,
            Service_Enrollment__r.Copy2_Street_2__c,Service_Enrollment__r.Copy2_City__c,
            Service_Enrollment__r.Copy2_State__c,Service_Enrollment__r.Copy2_Zip_Code__c,
            Account.Name,
                (SELECT ID,Opportunity.Owner.Initials__c,Description,Quantity,UnitPrice,TotalPrice,
                Product2.Charge_Type__c,Time_Entry__r.Entry_Date__c
                FROM OpportunityLineItems)
            FROM opportunity
            WHERE ID in: opportunityList]){
                opportunityLists.add(op);
        }
        opportunities = opportunityLists;
    }
}