force-app/main/default/objects/Contact/fields/Disbursement_Creation_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Disbursement_Creation_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Disbursement Creation Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EIN__c.field-meta.xml
<CustomField>
    <fullName>EIN__c</fullName>
    <label>EIN</label>
    <length>9</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Living_City__c.field-meta.xml
<CustomField>
    <fullName>Living_City__c</fullName>
    <label>Living City</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Living_Situation__c.field-meta.xml
<CustomField>
    <fullName>Living_Situation__c</fullName>
    <label>Living Situation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Independent</fullName>
            </value>
            <value>
                <fullName>Someone else&apos;s household</fullName>
            </value>
            <value>
                <fullName>Group care facility</fullName>
            </value>
            <value>
                <fullName>Skilled nursing facility</fullName>
            </value>
            <value>
                <fullName>Assisted living facility</fullName>
            </value>
            <value>
                <fullName>Hospital</fullName>
            </value>
            <value>
                <fullName>Institution, hospital, or nursing home</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Lives independently in own home or apartment</fullName>
                <isActive>false</isActive>
                <label>Lives independently in own home or apartment</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Living_State__c.field-meta.xml
<CustomField>
    <fullName>Living_State__c</fullName>
    <label>Living State</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States_Abreviations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Living_Street_1__c.field-meta.xml
<CustomField>
    <fullName>Living_Street_1__c</fullName>
    <label>Living Street 1</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Living_Street_2__c.field-meta.xml
<CustomField>
    <fullName>Living_Street_2__c</fullName>
    <label>Living Street 2</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Living_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Living_Zip_Code__c</fullName>
    <label>Living Zip Code</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Never married</fullName>
            </value>
            <value>
                <fullName>Married</fullName>
            </value>
            <value>
                <fullName>Separated</fullName>
            </value>
            <value>
                <fullName>Divorced</fullName>
            </value>
            <value>
                <fullName>Widowed</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Capt.</fullName>
            </value>
            <value>
                <fullName>CDR</fullName>
            </value>
            <value>
                <fullName>Col.</fullName>
            </value>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>Hon.</fullName>
            </value>
            <value>
                <fullName>Judge</fullName>
            </value>
            <value>
                <fullName>Major</fullName>
            </value>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
            <value>
                <fullName>Ms.</fullName>
            </value>
            <value>
                <fullName>Prof.</fullName>
            </value>
            <value>
                <fullName>Rev,</fullName>
                <label>Rev.</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Social_Security_Number__c.field-meta.xml
<CustomField>
    <fullName>Social_Security_Number__c</fullName>
    <label>Social Security Number</label>
    <length>11</length>
    <maskChar>asterisk</maskChar>
    <maskType>ssn</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Suffix_individual__c.field-meta.xml
<CustomField>
    <fullName>Suffix_individual__c</fullName>
    <label>Suffix</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Truelink_Disability_Designation__c.field-meta.xml
<CustomField>
    <fullName>Truelink_Disability_Designation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Truelink Disability Designation</label>
    <referenceTo>Truelink_Disability_Designation__c</referenceTo>
    <relationshipLabel>Parties</relationshipLabel>
    <relationshipName>Parties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Salutation_Translation__mdt/Salutation_Translation__mdt.object-meta.xml
<CustomObject>
    <label>Salutation Translation</label>
    <pluralLabel>Salutation Translations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Salutation_Translation__mdt/fields/Target_Value__c.field-meta.xml
<CustomField>
    <fullName>Target_Value__c</fullName>
    <label>Target Value</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr</fullName>
                <default>true</default>
                <label>Mr</label>
            </value>
            <value>
                <fullName>Mrs</fullName>
            </value>
            <value>
                <fullName>Miss</fullName>
            </value>
            <value>
                <fullName>Ms</fullName>
            </value>
            <value>
                <fullName>Mx</fullName>
            </value>
            <value>
                <fullName>Dr</fullName>
            </value>
            <value>
                <fullName>Jr</fullName>
            </value>
            <value>
                <fullName>II</fullName>
            </value>
            <value>
                <fullName>III</fullName>
            </value>
            <value>
                <fullName>IV</fullName>
            </value>
            <value>
                <fullName>None</fullName>
                <isActive>false</isActive>
                <label>None</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/Service_Enrollment__c.object-meta.xml
<CustomObject>
    <label>Service Enrollment</label>
    <nameField>
        <label>Service Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Enrollment__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Case_Manager__c.field-meta.xml
<CustomField>
    <fullName>Case_Manager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Manager</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Service_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Case_Manager_ID__c.field-meta.xml
<CustomField>
    <fullName>Case_Manager_ID__c</fullName>
    <formula>CASESAFEID(Case_Manager__r.Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Manager ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Living_Situation__c.field-meta.xml
<CustomField>
    <fullName>Living_Situation__c</fullName>
    <label>Living Situation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Living_Situation</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Service_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Service_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Enrollment</label>
    <referenceTo>Service_Enrollment__c</referenceTo>
    <relationshipLabel>Service Enrollments</relationshipLabel>
    <relationshipName>Service_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Trust__c.field-meta.xml
<CustomField>
    <fullName>Trust__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trust</label>
    <referenceTo>Trust__c</referenceTo>
    <relationshipLabel>Service Enrollments</relationshipLabel>
    <relationshipName>Service_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Truelink_Disability_Designation__c/Truelink_Disability_Designation__c.object-meta.xml
<CustomObject>
    <label>Truelink Disability Designation</label>
    <nameField>
        <label>Truelink Disability Designation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Truelink Disability Designations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Truelink_Disability_Designation__c/fields/Truelink_Internal_ID__c.field-meta.xml
<CustomField>
    <fullName>Truelink_Internal_ID__c</fullName>
    <label>Truelink Internal ID</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trust__c/Trust__c.object-meta.xml
<CustomObject>
    <description>Record the history of trust agreements for a beneficiary</description>
    <label>Trust</label>
    <nameField>
        <label>Trust ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trusts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trust__c/fields/Case_Manager__c.field-meta.xml
<CustomField>
    <fullName>Case_Manager__c</fullName>
    <formula>Service_Enrollment__r.Case_Manager__r.FirstName +&quot; &quot;+ Service_Enrollment__r.Case_Manager__r.LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Case Manager</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trust__c/fields/EIN__c.field-meta.xml
<CustomField>
    <fullName>EIN__c</fullName>
    <label>EIN</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trust__c/fields/Service_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Service_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Enrollment</label>
    <referenceTo>Service_Enrollment__c</referenceTo>
    <relationshipLabel>Trusts</relationshipLabel>
    <relationshipName>Trusts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trust__c/fields/Tax_Id_Number_Type__c.field-meta.xml
<CustomField>
    <fullName>Tax_Id_Number_Type__c</fullName>
    <label>Tax Id Number Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ein</fullName>
            </value>
            <value>
                <fullName>ssn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trust__c/fields/Trust_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Trust_Portfolio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trust Portfolio</label>
    <referenceTo>Trust_Portfolio__c</referenceTo>
    <relationshipLabel>Trusts</relationshipLabel>
    <relationshipName>Trusts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trust_Portfolio__c/Trust_Portfolio__c.object-meta.xml
<CustomObject>
    <label>Trust Portfolio</label>
    <nameField>
        <label>Trust Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trust Portfolios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trust_Portfolio__c/fields/True_Link_Portfolio_ID__c.field-meta.xml
<CustomField>
    <fullName>True_Link_Portfolio_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>TrueLink Portfolio ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Trust_Portfolio__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Portfolio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Living_Situation.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Homeless</fullName>
    </customValue>
    <customValue>
        <fullName>Incarcerated</fullName>
    </customValue>
    <customValue>
        <fullName>Lives Independently</fullName>
    </customValue>
    <customValue>
        <fullName>Lives in Facility or Hospital</fullName>
    </customValue>
    <customValue>
        <fullName>Lives in Vehicle</fullName>
    </customValue>
    <customValue>
        <fullName>Lives with Family</fullName>
    </customValue>
    <customValue>
        <fullName>Lives with Roommates</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Group care facility</fullName>
        <isActive>false</isActive>
        <label>Group care facility</label>
    </customValue>
    <customValue>
        <fullName>Skilled nursing facility</fullName>
        <isActive>false</isActive>
        <label>Skilled nursing facility</label>
    </customValue>
    <customValue>
        <fullName>Assisted living facility</fullName>
        <isActive>false</isActive>
        <label>Assisted living facility</label>
    </customValue>
    <customValue>
        <fullName>Hospital</fullName>
        <isActive>false</isActive>
        <label>Hospital</label>
    </customValue>
    <customValue>
        <fullName>Independent</fullName>
        <isActive>false</isActive>
        <label>Independent</label>
    </customValue>
    <customValue>
        <fullName>Institution, hospital, or nursing home</fullName>
        <isActive>false</isActive>
        <label>Institution, hospital, or nursing home</label>
    </customValue>
    <customValue>
        <fullName>Someone else&apos;s household</fullName>
        <isActive>false</isActive>
        <label>Someone else&apos;s household</label>
    </customValue>
    <masterLabel>Living Situation</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/States_Abreviations.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>AL</fullName>
    </customValue>
    <customValue>
        <fullName>AK</fullName>
    </customValue>
    <customValue>
        <fullName>AZ</fullName>
    </customValue>
    <customValue>
        <fullName>AR</fullName>
    </customValue>
    <customValue>
        <fullName>CA</fullName>
    </customValue>
    <customValue>
        <fullName>CO</fullName>
    </customValue>
    <customValue>
        <fullName>CT</fullName>
    </customValue>
    <customValue>
        <fullName>DE</fullName>
    </customValue>
    <customValue>
        <fullName>DC</fullName>
    </customValue>
    <customValue>
        <fullName>FL</fullName>
    </customValue>
    <customValue>
        <fullName>GA</fullName>
    </customValue>
    <customValue>
        <fullName>HI</fullName>
    </customValue>
    <customValue>
        <fullName>ID</fullName>
    </customValue>
    <customValue>
        <fullName>IL</fullName>
    </customValue>
    <customValue>
        <fullName>IN</fullName>
    </customValue>
    <customValue>
        <fullName>IA</fullName>
    </customValue>
    <customValue>
        <fullName>KS</fullName>
    </customValue>
    <customValue>
        <fullName>KY</fullName>
    </customValue>
    <customValue>
        <fullName>LA</fullName>
    </customValue>
    <customValue>
        <fullName>ME</fullName>
    </customValue>
    <customValue>
        <fullName>MD</fullName>
    </customValue>
    <customValue>
        <fullName>MA</fullName>
    </customValue>
    <customValue>
        <fullName>MI</fullName>
    </customValue>
    <customValue>
        <fullName>MN</fullName>
    </customValue>
    <customValue>
        <fullName>MS</fullName>
    </customValue>
    <customValue>
        <fullName>MO</fullName>
    </customValue>
    <customValue>
        <fullName>MT</fullName>
    </customValue>
    <customValue>
        <fullName>NE</fullName>
    </customValue>
    <customValue>
        <fullName>NV</fullName>
    </customValue>
    <customValue>
        <fullName>NH</fullName>
    </customValue>
    <masterLabel>States Abreviations</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TruelinkBeneficiaryRequestBuilder.cls
public class TruelinkBeneficiaryRequestBuilder { 
    public TruelinkBeneficiaryRequestWrapper build(String partyId, String trustPartyId, String trustBeneficiaryid, Boolean isUpdate){
        map<string,string> labelVsTargetMap = new map<string,string>();
        map<id,Truelink_Disability_Designation__c> disabilities = new map<id,Truelink_Disability_Designation__c>();
        for(Salutation_Translation__mdt st : Salutation_Translation__mdt.getAll().values()){
            labelVsTargetMap.put(st.label,st.target_value__c);
        }
        for(Truelink_Disability_Designation__c tdd : [select Id, Name, Truelink_Internal_ID__c from Truelink_Disability_Designation__c ]){
            disabilities.put(tdd.Id,tdd);
        }
        Contact party = [Select Id, Salutation__c,firstname,Middle_Name__c,lastname,
                         Suffix_individual__c,email,EIN__c,Social_Security_Number__c,Birthdate,
                         MobilePhone,GenderIdentity,Living_Street_1__c,Living_Street_2__c,Living_City__c,Living_State__c,Living_Zip_Code__c,
                         Marital_Status__c, Truelink_Disability_Designation__c, Living_Situation__c
                         from contact where Id =: partyId];

        Truelink_Feature_Management__c feature = Truelink_Feature_Management__c.getOrgDefaults();

        trust__c trustParty = new trust__c();
        if(trustPartyId!=null && trustPartyId!=''){
            trustParty = [Select Id, Trust_Portfolio__r.True_Link_Portfolio_ID__c,Trust_Portfolio__r.Type__c,Service_Enrollment__r.Account_Number__c,Case_Manager__c,
                          Tax_Id_Number_Type__c,EIN__c,Service_Enrollment__r.Case_Manager__c,Service_Enrollment__r.Case_Manager__r.Case_Manager_ID__c,
                          Disbursement_Creation_Enabled__c,Charge_Initial_Set_up_Fee__c,Trust_Type__c,TL_EID__c, TL_BID__c,
 						  mail_statements__c, True_Link_First_Name_Suffix__c from trust__c where Id =: trustPartyId];
        }
        
        String sufix = '';
        if(party.Suffix_individual__c!=null && party.Suffix_individual__c!='' && party.Suffix_individual__c.contains('.')){
            sufix = party.Suffix_individual__c.replace('.','');
        }else{
            sufix = party.Suffix_individual__c;
        }
        
        String prefix = '';
        if(party.Salutation__c!=null && party.Salutation__c!='' && party.Salutation__c.contains('.')){
            prefix = party.Salutation__c.replace('.','');
        }else{
            prefix = party.Salutation__c;
        }
        
        TruelinkBeneficiaryRequestWrapper reqWrapper = new TruelinkBeneficiaryRequestWrapper(isUpdate);
        if(isUpdate)
            reqWrapper.data.id = trustBeneficiaryid;    
        reqWrapper.data.attributes.email = party.email;
        reqWrapper.data.attributes.mobile = party.MobilePhone;
        reqWrapper.data.attributes.dob = party.Birthdate!=null?TruelinkRestUtil.formatDate(party.Birthdate):null;
        reqWrapper.data.attributes.gender = party.GenderIdentity;
        if(feature.Sync_Marital_Status__c == true){
            reqWrapper.data.attributes.maritalStatus = party.Marital_Status__c;
        }
        if(feature.Sync_Living_Situation__c == true){
            reqWrapper.data.attributes.livingSituation = party.Living_Situation__c;
        }
        reqWrapper.data.attributes.firstName = party.firstname;
        if(!String.isBlank(trustParty.True_Link_First_Name_Suffix__c)){
            reqWrapper.data.attributes.firstName = reqWrapper.data.attributes.firstName + ' (' + trustParty.True_Link_First_Name_Suffix__c+ ')';
        }
        reqWrapper.data.attributes.middleName = party.Middle_Name__c;
        reqWrapper.data.attributes.lastName = party.lastname;
        if(trustParty.Service_Enrollment__r.Case_Manager__c!=null && !String.isBlank(trustParty.Service_Enrollment__r.Case_Manager__r.Case_Manager_ID__c)){
            reqWrapper.data.attributes.lastName = reqWrapper.data.attributes.lastName + ' ' + trustParty.Service_Enrollment__r.Case_Manager__r.Case_Manager_ID__c;
        }

        reqWrapper.data.attributes.ein = trustParty.EIN__c;//Internal_Account_Number__c,Case_Manager__c,
        //reqWrapper.data.attributes.ssn = party.Social_Security_Number__c ;
        reqWrapper.data.attributes.taxIdNumberType = trustParty.Tax_Id_Number_Type__c;
        
        reqWrapper.data.attributes.disallowDisbursementRequests = !trustParty.Disbursement_Creation_Enabled__c;
        reqWrapper.data.attributes.chargeSetupFee = trustParty.Charge_Initial_Set_up_Fee__c;
        //revert the logic
        reqWrapper.data.attributes.externalId = trustParty.TL_EID__c;
        reqWrapper.data.attributes.beneficiaryId = trustParty.TL_BID__c;
        
        if(!isUpdate){
 			
            if(!String.isBlank(party.Living_Street_1__c))
            	reqWrapper.data.relationships.address.data.attributes.street1 = party.Living_Street_1__c;
            if(!String.isBlank(party.Living_Street_2__c))
            	reqWrapper.data.relationships.address.data.attributes.street2 = party.Living_Street_2__c;
            if(!String.isBlank(party.Living_City__c))
            	reqWrapper.data.relationships.address.data.attributes.city = party.Living_City__c;
            if(!String.isBlank(party.Living_State__c))
            	reqWrapper.data.relationships.address.data.attributes.state = party.Living_State__c;
            if(!String.isBlank(party.Living_Zip_Code__c))
            	reqWrapper.data.relationships.address.data.attributes.zip = party.Living_Zip_Code__c;
            
            reqWrapper.data.relationships.activePortfolio.data.type = 'portfolio'; //trustParty.Trust_Portfolio__r.Type__c;
            reqWrapper.data.relationships.activePortfolio.data.id = trustParty.Trust_Portfolio__r.True_Link_Portfolio_ID__c;
            
            reqWrapper.data.attributes.prefix = labelVsTargetMap.containskey(prefix) ? labelVsTargetMap.get(prefix) : null;
            reqWrapper.data.attributes.suffix = labelVsTargetMap.containskey(sufix) ? labelVsTargetMap.get(sufix) : null;
            reqWrapper.data.attributes.externalId = trustParty.TL_Eid__c;

            reqWrapper.data.attributes.mailStatement = trustParty.Mail_statements__c;
        }

        // relationships is only auto-initialized for creates (see TruelinkBeneficiaryRequestWrapper's
        // isUpdate constructor) - for updates, set up just enough to carry disabilityDesignation without
        // pulling address/activePortfolio (still empty) into the update payload.
        if(reqWrapper.data.relationships == null){
            reqWrapper.data.relationships = new TruelinkBeneficiaryRequestWrapper.Relationships();
            reqWrapper.data.relationships.address = null;
            reqWrapper.data.relationships.activePortfolio = null;
        }

        if(feature.Sync_Disability_Designation__c == true){
            if(!String.isBlank(party.Truelink_Disability_Designation__c) && !disabilities.isEmpty() && disabilities.containskey(party.Truelink_Disability_Designation__c)){
                reqWrapper.data.relationships.disabilityDesignation.data.type = 'disability_designation';
                reqWrapper.data.relationships.disabilityDesignation.data.id = disabilities.get(party.Truelink_Disability_Designation__c).Truelink_Internal_ID__c;
            }
            else {
                reqWrapper.data.relationships.disabilityDesignation = null;
            }
        }
        else {
            reqWrapper.data.relationships.disabilityDesignation = null;
        }

        return reqWrapper;
    }
    
    public TruelinkBeneficiaryAddressRequestWrapper buildAddress(String partyId, String addressId){
        Contact party = [Select Id, Salutation__c,firstname,Middle_Name__c,lastname,
                         Suffix_individual__c,email,EIN__c,Social_Security_Number__c,Birthdate,
                         MobilePhone,GenderIdentity,Living_Street_1__c,Living_Street_2__c,Living_City__c,Living_State__c,Living_Zip_Code__c,
                         Marital_Status__c, Truelink_Disability_Designation__c //,Living_Situation__c
                         from contact where Id =: partyId];
        
        
        TruelinkBeneficiaryAddressRequestWrapper reqWrapper = new TruelinkBeneficiaryAddressRequestWrapper();
        if(!String.isBlank(party.Living_Street_1__c))
        	reqWrapper.data.attributes.street1 = party.Living_Street_1__c;
        if(!String.isBlank(party.Living_Street_2__c))
        	reqWrapper.data.attributes.street2 = party.Living_Street_2__c;
        reqWrapper.data.type = 'address';
        //reqWrapper.data.id = addressId;
        if(!String.isBlank(party.Living_City__c))
        	reqWrapper.data.attributes.city = party.Living_City__c;
        if(!String.isBlank(party.Living_State__c))
        	reqWrapper.data.attributes.state = party.Living_State__c;
        if(!String.isBlank(party.Living_Zip_Code__c))
        	reqWrapper.data.attributes.zip = party.Living_Zip_Code__c;
        
        return reqWrapper;
    }
    
    public TruelinkBeneficiaryRequestWrapper buildRequestForTrustDisbursement(String trustId){
        trust__c trust = new trust__c();
        if(trustId!=null && trustId!=''){
            trust = [Select Disbursement_Creation_Enabled__c,Mail_statements__c from trust__c where Id =: trustId];
        }
        
        TruelinkBeneficiaryRequestWrapper reqWrapper = new TruelinkBeneficiaryRequestWrapper(true);
        reqWrapper.data.attributes.disallowDisbursementRequests = !Boolean.valueof(trust.Disbursement_Creation_Enabled__c);
        reqWrapper.data.attributes.mailStatement = trust.Mail_statements__c;

        return reqWrapper;
    }
    
    public TruelinkBeneficiaryRequestWrapper buildRequestForEinBidUpdate(String trustId){
        trust__c trust = new trust__c();
        if(trustId!=null && trustId!=''){
            trust = [Select Internal_Account_Number__c,Trust_Type__c,TL_EID__c,TL_BID__c from trust__c where Id =: trustId];
        }
        
        TruelinkBeneficiaryRequestWrapper reqWrapper = new TruelinkBeneficiaryRequestWrapper(true);
		reqWrapper.data.attributes.externalId = trust.TL_EID__c;
        reqWrapper.data.attributes.beneficiaryId = trust.TL_BID__c;

        return reqWrapper;
    }
}