force-app/main/default/objects/Contact/fields/Original_System_ID__c.field-meta.xml
<CustomField>
    <fullName>Original_System_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Original System ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Active Referral Source</fullName>
            </value>
            <value>
                <fullName>Inactive Referral Source</fullName>
            </value>
            <value>
                <fullName>Active Inquiry</fullName>
            </value>
            <value>
                <fullName>Inactive Inquiry</fullName>
            </value>
            <value>
                <fullName>Applicant: Active</fullName>
            </value>
            <value>
                <fullName>Applicant: Inactive</fullName>
            </value>
            <value>
                <fullName>Active Beneficiary</fullName>
            </value>
            <value>
                <fullName>Future-Funded Beneficiary</fullName>
            </value>
            <value>
                <fullName>Future-Funded Inactive</fullName>
            </value>
            <value>
                <fullName>Inactive-Deceased</fullName>
            </value>
            <value>
                <fullName>Inactive-Insufficient Funds</fullName>
            </value>
            <value>
                <fullName>Closed-Deceased</fullName>
            </value>
            <value>
                <fullName>Closed-Insufficient Funds</fullName>
            </value>
            <value>
                <fullName>Active Non-Beneficiary</fullName>
            </value>
            <value>
                <fullName>Inactive Non-Beneficiary</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <default>true</default>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Period</label>
    <referenceTo>Periods__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Service_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Service_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Enrollment</label>
    <referenceTo>Service_Enrollment__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Payment_Batch__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Entry_Date__c.field-meta.xml
<CustomField>
    <fullName>Entry_Date__c</fullName>
    <formula>Time_Entry__r.Entry_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Time_Entry__c.field-meta.xml
<CustomField>
    <fullName>Time_Entry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Time Entry</label>
    <referenceTo>Time_Entry__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Periods__c/Periods__c.object-meta.xml
<CustomObject>
    <label>Period</label>
    <nameField>
        <label>Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Periods__c/fields/Is_Closed__c.field-meta.xml
<CustomField>
    <fullName>Is_Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Periods__c/fields/Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_End_Date__c</fullName>
    <label>Period End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Periods__c/fields/Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_Start_Date__c</fullName>
    <label>Period Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Original_System_ID__c.field-meta.xml
<CustomField>
    <fullName>Original_System_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Original System ID</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Original_System_ID__c.field-meta.xml
<CustomField>
    <fullName>Original_System_ID__c</fullName>
    <externalId>true</externalId>
    <label>Original System ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/Service_Enrollment__c.object-meta.xml
<CustomObject>
    <label>Service Enrollment</label>
    <nameField>
        <label>Service Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Enrollment__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Beneficiary</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Enrollments</relationshipLabel>
    <relationshipName>Service_Enrollments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>xService</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Enrollments</relationshipLabel>
    <relationshipName>Service_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Service_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Service_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Enrollment</label>
    <referenceTo>Service_Enrollment__c</referenceTo>
    <relationshipLabel>Service Enrollments</relationshipLabel>
    <relationshipName>Service_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Future</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Entry__c/Time_Entry__c.object-meta.xml
<CustomObject>
    <label>Time Entry</label>
    <nameField>
        <label>Time Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Entry__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beneficiary</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Entry_Date__c.field-meta.xml
<CustomField>
    <fullName>Entry_Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Opportunity_Product__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipName>Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Period</label>
    <referenceTo>Periods__c</referenceTo>
    <relationshipName>Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <inlineHelpText>Use hour increments: 15 minutes = 0.25, 30 minutes = 0.5, 45 minutes = 0.75</inlineHelpText>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Service_Code__c.field-meta.xml
<CustomField>
    <fullName>Service_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Code</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Service_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Service_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Enrollment</label>
    <referenceTo>Service_Enrollment__c</referenceTo>
    <relationshipName>Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVE</fullName>
                <default>true</default>
                <label>ACTIVE</label>
            </value>
            <value>
                <fullName>APPROVED</fullName>
            </value>
            <value>
                <fullName>INVOICED</fullName>
            </value>
            <value>
                <fullName>CANCELED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InvoicingBatchTest.cls
@isTest
public class InvoicingBatchTest {
    @testSetup
    static void setupTestData() {
        // Create test periods
        Periods__c testPeriod = new Periods__c(
            Name = 'Test Period',
            Is_Closed__c = false,
            Period_Start_Date__c = Date.today().addMonths(-1),
            Period_End_Date__c = Date.today().addDays(15)
        );
        insert testPeriod;

        // Create test pricebook
         Id pricebookId = Test.getStandardPricebookId();
        Pricebook2 testPricebook = new Pricebook2(
            Id = pricebookId,
            IsActive = true
        );
        update testPricebook;
        
        Service__c ser = new Service__c(name = 'Test Service');
        insert ser;

        // Create test products and pricebook entries
        Product2 testProduct = new Product2(Name = 'Test Product', IsActive = true);
        insert testProduct;

        PricebookEntry testPricebookEntry = new PricebookEntry(
            Pricebook2Id = testPricebook.Id,
            Product2Id = testProduct.Id,
            UnitPrice = 100.0,
            Original_System_ID__c = 'test',
            IsActive = true
        );
        insert testPricebookEntry;

        

        // Create test accounts and contacts
        Account testAccount = new Account(Name = 'Test Account');
        insert testAccount;

        Contact testContact = new Contact(
            LastName = 'Test Contact',
            AccountId = testAccount.Id
        );
        insert testContact;

        // Create test service enrollments
        Service_Enrollment__c testServiceEnrollment = new Service_Enrollment__c(
            Name = 'Test Enrollment',
            Client__c = testContact.Id,
            Service__c = ser.Id,
            Status__c = 'Pending',
            Account_Number__c = 'Test',
            Date_Closed__c = Date.today().addDays(30)
        );
        insert testServiceEnrollment;
    
        opportunity oppr = new opportunity(Name='testing DIE 4/6/2015' ,  AccountId= testAccount.Id,StageName = 'Invoiced', 
                                   CloseDate = Date.today());
        insert oppr;
        
        OpportunityLineItem oli = new OpportunityLineItem(
             OpportunityId = oppr.Id,
             Quantity = 5,
             PricebookEntryId = testPricebookEntry.Id,
             TotalPrice = 5 * testPricebookEntry.UnitPrice
        );
        insert oli;     
        
        // Create test charges
        Time_Entry__c testCharge = new Time_Entry__c(
            Entry_date__c = Date.today(),
            Client__c = testContact.Id,
            Description__c = 'Test Charge',
            Service_Enrollment__c = testServiceEnrollment.Id,
            Quantity__c = 1,
            Service_Code__c = testProduct.Id,
            Unit_Price__c = 100.0,
            Period__c = testPeriod.Id,
            Approved__c = true,
            Status__c = 'APPROVED',
            Opportunity_Product__c = oli.Id
        );
        insert testCharge;
    }

    @isTest
    static void testInvoicingBatch() {
        Periods__c testPeriod = [SELECT Id FROM Periods__c LIMIT 1];
        Test.startTest();
        InvoicingBatch batch = new InvoicingBatch(testPeriod.Id);
        Database.executeBatch(batch);
        Test.stopTest();

        /*// Verify Opportunities
        List<Opportunity> opportunities = [SELECT Id, Name, AccountId, Service_Enrollment__c, StageName, Period__c, Pricebook2Id, RecordTypeId FROM Opportunity];
        //System.assertEquals(1, opportunities.size(), 'There should be 1 opportunity created');
        Opportunity opp = opportunities[0];
        //System.assertEquals('Test Contact-Te', opp.Name.substring(0, 15), 'Opportunity name should start with the service enrollment name');
        System.assertEquals('Invoiced', opp.StageName, 'Opportunity stage should be Invoiced');
        System.assertEquals(testPeriod.Id, opp.Period__c, 'Opportunity period should match the test period');
        System.assertEquals([SELECT Id FROM Pricebook2 WHERE IsActive = true LIMIT 1].Id, opp.Pricebook2Id, 'Opportunity pricebook should be active pricebook');
        System.assertEquals([SELECT Id FROM RecordType WHERE Name = 'Client Invoice' LIMIT 1].Id, opp.RecordTypeId, 'Opportunity record type should be Client Invoice');

        // Verify Opportunity Line Items
        List<OpportunityLineItem> opportunityLineItems = [SELECT Id, OpportunityId, Quantity, Description, UnitPrice, Product2Id FROM OpportunityLineItem];
        System.assertEquals(1, opportunityLineItems.size(), 'There should be 1 opportunity line item created');
        OpportunityLineItem oppItem = opportunityLineItems[0];
        System.assertEquals(opp.Id, oppItem.OpportunityId, 'Opportunity Line Item should be linked to the correct Opportunity');
        System.assertEquals(1, oppItem.Quantity, 'Opportunity Line Item quantity should be 1');
        System.assertEquals('Test Charge', oppItem.Description, 'Opportunity Line Item description should match the test charge description');
        System.assertEquals(100.0, oppItem.UnitPrice, 'Opportunity Line Item unit price should match the test charge unit price');
        System.assertEquals([SELECT Id FROM Product2 WHERE Name = 'Test Product' LIMIT 1].Id, oppItem.Product2Id, 'Opportunity Line Item product should be the test product');

        // Verify Charges
        List<Time_Entry__c> charges = [SELECT Id, Status__c FROM Time_Entry__c WHERE Status__c = 'INVOICED'];
        System.assertEquals(1, charges.size(), 'There should be 1 charge updated to INVOICED status');*/
    }
}