force-app/main/default/objects/Contact/fields/Original_System_ID__c.field-meta.xml
<CustomField>
    <fullName>Original_System_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Original System ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Active Referral Source</fullName>
            </value>
            <value>
                <fullName>Inactive Referral Source</fullName>
            </value>
            <value>
                <fullName>Active Inquiry</fullName>
            </value>
            <value>
                <fullName>Inactive Inquiry</fullName>
            </value>
            <value>
                <fullName>Applicant: Active</fullName>
            </value>
            <value>
                <fullName>Applicant: Inactive</fullName>
            </value>
            <value>
                <fullName>Active Beneficiary</fullName>
            </value>
            <value>
                <fullName>Future-Funded Beneficiary</fullName>
            </value>
            <value>
                <fullName>Future-Funded Inactive</fullName>
            </value>
            <value>
                <fullName>Inactive-Deceased</fullName>
            </value>
            <value>
                <fullName>Inactive-Insufficient Funds</fullName>
            </value>
            <value>
                <fullName>Closed-Deceased</fullName>
            </value>
            <value>
                <fullName>Closed-Insufficient Funds</fullName>
            </value>
            <value>
                <fullName>Active Non-Beneficiary</fullName>
            </value>
            <value>
                <fullName>Inactive Non-Beneficiary</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <default>true</default>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Non_Billable__c.field-meta.xml
<CustomField>
    <fullName>Non_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Non-Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Original_System_ID__c.field-meta.xml
<CustomField>
    <fullName>Original_System_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Original System ID</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/Time_Entry_Category__c.field-meta.xml
<CustomField>
    <fullName>Time_Entry_Category__c</fullName>
    <label>Time Entry Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Entry_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/Service_Enrollment__c.object-meta.xml
<CustomObject>
    <label>Service Enrollment</label>
    <nameField>
        <label>Service Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Enrollment__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Beneficiary</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Enrollments</relationshipLabel>
    <relationshipName>Service_Enrollments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Service_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Service_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Enrollment</label>
    <referenceTo>Service_Enrollment__c</referenceTo>
    <relationshipLabel>Service Enrollments</relationshipLabel>
    <relationshipName>Service_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Future</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Entry__c/Time_Entry__c.object-meta.xml
<CustomObject>
    <label>Time Entry</label>
    <nameField>
        <label>Time Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Entry__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beneficiary</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Entry_Date__c.field-meta.xml
<CustomField>
    <fullName>Entry_Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Hours__c.field-meta.xml
<CustomField>
    <fullName>Hours__c</fullName>
    <label>Hours</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Minutes__c.field-meta.xml
<CustomField>
    <fullName>Minutes__c</fullName>
    <label>Minutes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>42</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>54</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Non_billable__c.field-meta.xml
<CustomField>
    <fullName>Non_billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Non-billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <inlineHelpText>Use hour increments: 15 minutes = 0.25, 30 minutes = 0.5, 45 minutes = 0.75</inlineHelpText>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Service_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Service_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Enrollment</label>
    <referenceTo>Service_Enrollment__c</referenceTo>
    <relationshipName>Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVE</fullName>
                <default>true</default>
                <label>ACTIVE</label>
            </value>
            <value>
                <fullName>APPROVED</fullName>
            </value>
            <value>
                <fullName>INVOICED</fullName>
            </value>
            <value>
                <fullName>CANCELED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Time_Entry_Category__c.field-meta.xml
<CustomField>
    <fullName>Time_Entry_Category__c</fullName>
    <label>Time Entry Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Entry_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Time_Entry_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>HOURLY SERVICE</fullName>
        <default>true</default>
        <label>HOURLY SERVICE</label>
    </customValue>
    <customValue>
        <fullName>ADMINISTRATIVE TIME</fullName>
    </customValue>
    <customValue>
        <fullName>DIRECT EXPENSE</fullName>
    </customValue>
    <customValue>
        <fullName>FEES</fullName>
    </customValue>
    <customValue>
        <fullName>Time</fullName>
        <isActive>false</isActive>
        <label>Time</label>
    </customValue>
    <customValue>
        <fullName>Expense</fullName>
        <isActive>false</isActive>
        <label>Expense</label>
    </customValue>
    <masterLabel>Time Entry Category</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BulkTimeEntryUtilsTest.cls
@isTest
public class BulkTimeEntryUtilsTest {
	@testSetup
    static void setupTestData() {
        // Create test contacts
        Contact testContact = new Contact(LastName = 'Test Contact');
        insert testContact;
        

        
        // Create test service enrollments
        Service_Enrollment__c testServiceEnrollment = new Service_Enrollment__c(
            Name = 'Test Enrollment',
            Client__c = testContact.Id,
            Status__c = 'Pending',
            Account_Number__c = 'Test'
        );
        insert testServiceEnrollment;
        
        // Create test products
        Product2 testProduct = new Product2(Name = 'Test Product', Time_Entry_Category__c = 'FEES', IsActive = true);
        Id pricebookId = Test.getStandardPricebookId();
        Pricebook2 standardPricebook = new Pricebook2(
            Id = pricebookId,
            IsActive = true
        );
        insert testProduct;
        
        // Create test pricebook
        PricebookEntry testPricebookEntry = new PricebookEntry(
            Pricebook2Id = standardPricebook.Id,
            Product2Id = testProduct.Id,
            Original_System_ID__c = 'test',
            UnitPrice = 100.0,
            IsActive = true
        );
        insert testPricebookEntry;
        
        // Create test charges
        Time_Entry__c testCharge = new Time_Entry__c(
            Name = 'Test Charge',
            Client__c = testContact.Id,
            Time_Entry_Category__c = 'FEES',
            Hours__c = '2',
            Minutes__c = '30',
            Quantity__c = 1,
            Non_billable__c = false,
            Service_Enrollment__c = testServiceEnrollment.Id,
            Entry_date__c = Date.today(),
            Unit_Price__c = 100.0,
            Status__c = 'Active'
        );
        insert testCharge;
    }
    
    @isTest
    static void testGetClients() {
        Test.startTest();
        List<Contact> clients = BulkTimeEntryUtils.getClients();
        Test.stopTest();
        
        System.assertNotEquals(0, clients.size(), 'Clients should not be empty');
    }
    
    @isTest
    static void testGetServiceEntollment() {
        Contact testContact = [SELECT Id FROM Contact LIMIT 1];
        
        Test.startTest();
        List<Service_Enrollment__c> serviceEnrollments = BulkTimeEntryUtils.getServiceEntollment(testContact.Id);
        Test.stopTest();
        
        System.assertNotEquals(0, serviceEnrollments.size(), 'Service Enrollments should not be empty');
    }
    
    @isTest
    static void testGetBillingCode() {
        Test.startTest();
        List<Product2> billingCodes = BulkTimeEntryUtils.getBillingCode('FEES');
        Test.stopTest();
        
        System.assertNotEquals(0, billingCodes.size(), 'Billing Codes should not be empty');
    }
    
    @isTest
    static void testGetUnitPrice() {
        Product2 testProduct = [SELECT Id FROM Product2 WHERE Time_Entry_Category__c = 'FEES' LIMIT 1];
        
        Test.startTest();
        Double unitPrice = BulkTimeEntryUtils.getUnitPrice(testProduct.Id);
        Test.stopTest();
        
        System.assertNotEquals(100, unitPrice, 'Unit Price should not be null');
    }
    
    @isTest
    static void testGetCharges() {
        Test.startTest();
        List<Time_Entry__c> chargesToday = BulkTimeEntryUtils.getCharges('TODAY');
        List<Time_Entry__c> chargesTHIS_WEEK = BulkTimeEntryUtils.getCharges('THIS_WEEK');
        List<Time_Entry__c> chargesTHIS_MONTH = BulkTimeEntryUtils.getCharges('THIS_MONTH');
        List<Time_Entry__c> chargesLAST_MONTH = BulkTimeEntryUtils.getCharges('LAST_MONTH');
        Test.stopTest();
        
        System.assertNotEquals(0, chargesToday.size(), 'Charges for today should not be empty');
    }
}