force-app/main/default/objects/Contact/fields/Original_System_ID__c.field-meta.xml
<CustomField>
    <fullName>Original_System_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Original System ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/Bill_To_Print_Date__c.field-meta.xml
<CustomField>
    <fullName>Bill_To_Print_Date__c</fullName>
    <label>Bill To Print Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Copy1_Print_Date__c.field-meta.xml
<CustomField>
    <fullName>Copy1_Print_Date__c</fullName>
    <label>Copy1 Print Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Copy2_Email_Date__c.field-meta.xml
<CustomField>
    <fullName>Copy2_Email_Date__c</fullName>
    <label>Copy2 Email Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Copy2_Print_Date__c.field-meta.xml
<CustomField>
    <fullName>Copy2_Print_Date__c</fullName>
    <label>Copy2 Print Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Days_Aging_Range__c.field-meta.xml
<CustomField>
    <fullName>Days_Aging_Range__c</fullName>
    <formula>If(AND(Days_Aging__c &gt;1,Days_Aging__c&lt;31),&quot;1-30 Days&quot;,if(AND(Days_Aging__c &gt;30, Days_Aging__c&lt;61),&quot;31-60 Days&quot;,If(AND(Days_Aging__c &gt;60 , Days_Aging__c&lt;90),&quot;61-90 Days&quot;,if(Days_Aging__c&gt;90,&quot;90+ Days&quot;,&quot;&quot;))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Days Aging Range</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Mail_To_Print_Date__c.field-meta.xml
<CustomField>
    <fullName>Mail_To_Print_Date__c</fullName>
    <label>Mail To Print Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Payment_Status__c.field-meta.xml
<CustomField>
    <fullName>Payment_Status__c</fullName>
    <label>Payment Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Service_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Service_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Enrollment</label>
    <referenceTo>Service_Enrollment__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Charge_Type__c.field-meta.xml
<CustomField>
    <fullName>Charge_Type__c</fullName>
    <label>Charge Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CREDIT</fullName>
            </value>
            <value>
                <fullName>DIRECT EXPENSE</fullName>
            </value>
            <value>
                <fullName>HOURLY SERVICE</fullName>
            </value>
            <value>
                <fullName>FEES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Original_System_ID__c.field-meta.xml
<CustomField>
    <fullName>Original_System_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Original System ID</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Service__c/Service__c.object-meta.xml
<CustomObject>
    <label>Service</label>
    <nameField>
        <label>Service Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service__c/fields/Original_System_ID__c.field-meta.xml
<CustomField>
    <fullName>Original_System_ID__c</fullName>
    <externalId>true</externalId>
    <label>Original System ID</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/Service_Enrollment__c.object-meta.xml
<CustomObject>
    <label>Service Enrollment</label>
    <nameField>
        <label>Service Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Enrollment__c/fields/Account_Number__c.field-meta.xml
<CustomField>
    <fullName>Account_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Account Number</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Beneficiary</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Enrollments</relationshipLabel>
    <relationshipName>Service_Enrollments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Copy_1_Email__c.field-meta.xml
<CustomField>
    <fullName>Copy_1_Email__c</fullName>
    <label>Copy 1 Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Copy_1_Invoice_Options__c.field-meta.xml
<CustomField>
    <fullName>Copy_1_Invoice_Options__c</fullName>
    <label>Copy 1 Invoice Options</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Invoice_Options</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Copy_2_Email__c.field-meta.xml
<CustomField>
    <fullName>Copy_2_Email__c</fullName>
    <label>Copy 2 Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>xService</label>
    <referenceTo>Service__c</referenceTo>
    <relationshipLabel>Service Enrollments</relationshipLabel>
    <relationshipName>Service_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Service_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Service_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Enrollment</label>
    <referenceTo>Service_Enrollment__c</referenceTo>
    <relationshipLabel>Service Enrollments</relationshipLabel>
    <relationshipName>Service_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visualforce_PDF__c/Visualforce_PDF__c.object-meta.xml
<CustomObject>
    <label>Visualforce PDF</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visualforce PDFs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visualforce_PDF__c/fields/Fields_to_Update_For_Email__c.field-meta.xml
<CustomField>
    <fullName>Fields_to_Update_For_Email__c</fullName>
    <label>Fields to Update For Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visualforce_PDF__c/fields/Fields_to_Update_For_Print__c.field-meta.xml
<CustomField>
    <fullName>Fields_to_Update_For_Print__c</fullName>
    <label>Fields to Update For Print</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visualforce_PDF__c/fields/Fields_Values_to_Update_For_Email__c.field-meta.xml
<CustomField>
    <fullName>Fields_Values_to_Update_For_Email__c</fullName>
    <label>Fields Values to Update For Email</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visualforce_PDF__c/fields/Fields_Values_to_Update_For_Print__c.field-meta.xml
<CustomField>
    <fullName>Fields_Values_to_Update_For_Print__c</fullName>
    <label>Fields Values to Update For Print</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visualforce_PDF__c/fields/Print_Type__c.field-meta.xml
<CustomField>
    <fullName>Print_Type__c</fullName>
    <label>Print Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bulk</fullName>
            </value>
            <value>
                <fullName>Individual Record</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Visualforce_PDF__c/fields/Recipient_Address_Field__c.field-meta.xml
<CustomField>
    <fullName>Recipient_Address_Field__c</fullName>
    <label>Recipient Address Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visualforce_PDF__c/fields/Service_Enrollment_Master_Field__c.field-meta.xml
<CustomField>
    <fullName>Service_Enrollment_Master_Field__c</fullName>
    <label>Service Enrollment Master Field</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visualforce_PDF__c/fields/Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>Sub_Type__c</fullName>
    <inlineHelpText>This field can be use to filter a document type to something specific to the record. For example Shipping and Receiving use the same object. The Type field can be used to only display shippers or receivers.</inlineHelpText>
    <label>Sub-Type</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Visualforce_PDF__c/fields/Visual_Force_Page_Name__c.field-meta.xml
<CustomField>
    <fullName>Visual_Force_Page_Name__c</fullName>
    <label>Visual Force Page Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Invoice_Options.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Print</fullName>
    </customValue>
    <customValue>
        <fullName>Email</fullName>
    </customValue>
    <customValue>
        <fullName>Print and Email</fullName>
    </customValue>
    <masterLabel>Invoice Options</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BulkViewSelectorController_Test.cls
@isTest
public class BulkViewSelectorController_Test {
    @testSetup
    static void testDataSetup(){
         Contact cont=new Contact();
        cont.LastName='TestService';
        cont.FirstName ='Test Frist Name';
        insert cont;
        
        Service__c ser=new Service__c();
        ser.Name = 'Demo Service Name';
        insert ser;
        
        Service_Enrollment__c sr=new Service_Enrollment__c();
        sr.Service__c = ser.Id;
        sr.Account_Number__c='PL1288';
        sr.Copy_1_Invoice_Options__c='Email';
        sr.Copy_1_Email__c = 'test@test.com';
        sr.Client__c = cont.Id;
        insert sr;
        
        Service_Enrollment__c sr1=new Service_Enrollment__c();
        sr1.Service__c = ser.Id;
        sr1.Account_Number__c='PL12883';
        sr1.Copy_1_Invoice_Options__c='Print';
        sr1.Client__c = cont.Id;
        insert sr1;
        
        Opportunity op=new Opportunity();
        op.Name='demo';
        op.STAGENAME = 'Posted';
        op.Payment_Status__c = 'Open';
        op.CloseDate = Date.Today().addDays(-10);
        op.Service_Enrollment__c = sr.Id;
        op.Amount=240;
        insert op;
        
        Opportunity op1=new Opportunity();
        op1.Name='demo';
        op1.STAGENAME = 'Posted';
        op1.Payment_Status__c = 'Open';
        op1.CloseDate = Date.Today().addDays(-10);
        op1.Service_Enrollment__c = sr1.Id;
        op1.Amount=240;
        insert op1;
       
        Product2 pro2 = new Product2(Name='BXCD', isActive=true,Charge_Type__c='HOURLY SERVICE');
        insert pro2;
          
        PricebookEntry pbe2 =new PricebookEntry(unitprice=0.01,Product2Id=pro2.Id,Pricebook2Id=Test.getStandardPricebookId(),
                                                 isActive=true,UseStandardPrice = false,Original_System_ID__c='Test'+pro2.Id);
        insert pbe2;
        
        OpportunityLineItem OPplineitem2 = new OpportunityLineItem (Quantity=2, OpportunityId=op.Id,
                                                                    UnitPrice=0.01,PriceBookEntryId=pbe2.Id);
        insert OPplineitem2;
        
        
        Product2 pro2DirectExpence = new Product2(Name='BXCD', isActive=true,Charge_Type__c='DIRECT EXPENSE');
        insert pro2DirectExpence;
      
        
        PricebookEntry pbe2DirectExpence =new PricebookEntry(unitprice=0.01,Product2Id=pro2DirectExpence.Id,
        Pricebook2Id=Test.getStandardPricebookId(), isActive=true,UseStandardPrice = false,Original_System_ID__c='Test'+pro2DirectExpence.Id);
        insert pbe2DirectExpence;
              
        OpportunityLineItem OPplineitem2DirectExpence = new OpportunityLineItem (Quantity=2, OpportunityId=op.Id,
                                                                    UnitPrice=0.01,PriceBookEntryId=pbe2DirectExpence.Id);
        insert OPplineitem2DirectExpence;
        
        List<Visualforce_PDF__c> pdfs = new List<Visualforce_PDF__c>();
        Visualforce_PDF__c pdf1 = new Visualforce_PDF__c();
        pdf1.Service_Enrollment_Master_Field__c = 'Copy_1_Invoice_Options__c';
        pdf1.Object_API_Name__c = 'Opportunity';
        pdf1.Visual_Force_Page_Name__c = 'InvoiceTemplateCopy2';
        pdf1.File_Name__c = 'InvoiceTemplateCopy2';
        pdf1.Fields_to_Update_For_Email__c = 'Copy2_Email_Date__c';
        pdf1.Sub_Type__c = 'Email';
        pdf1.Recipient_Address_Field__c='Copy_2_Email__c';
        pdf1.Fields_Values_to_Update_For_Email__c='NOW';
        pdf1.Print_Type__c ='Individual Record';
        pdfs.add(pdf1);
        
        Visualforce_PDF__c pdf2 = new Visualforce_PDF__c();
        pdf2.Object_API_Name__c = 'Opportunity';
        pdf2.Service_Enrollment_Master_Field__c = 'Copy_1_Invoice_Options__c';
        pdf2.Visual_Force_Page_Name__c = 'InvoiceTemplateCopy2';
        pdf2.File_Name__c = 'InvoiceTemplateCopy2';
        pdf2.Fields_to_Update_For_Email__c = 'Copy2_Email_Date__c';
        pdf2.Sub_Type__c = 'Print';
        pdf2.Recipient_Address_Field__c='Copy_1_Email__c';
        pdf2.Fields_Values_to_Update_For_Email__c='NOW';
        pdf2.Print_Type__c ='Individual Record';
        pdfs.add(pdf2);
        
        Visualforce_PDF__c pdf3 = new Visualforce_PDF__c();
        pdf3.Object_API_Name__c = 'Opportunity';
        pdf3.Service_Enrollment_Master_Field__c = 'Copy_1_Invoice_Options__c';
        pdf3.Visual_Force_Page_Name__c = 'InvoiceTemplateCombined';
        pdf3.File_Name__c = 'InvoiceTemplateCombined_';
        pdf3.Fields_to_Update_For_Print__c = 'Copy1_Print_Date__c,Copy2_Print_Date__c,Mail_To_Print_Date__c,Bill_To_Print_Date__c';
        pdf3.Sub_Type__c = 'Print';
        pdf3.Recipient_Address_Field__c='Billing_Email__c,Copy_1_Email__c';
        pdf3.Fields_Values_to_Update_For_Print__c='NOW,NOW,NOW,NOW';
        pdf3.Print_Type__c ='Bulk';
        pdfs.add(pdf3);
        
        insert pdfs;
    }
    @isTest
    static void invoiceTemplateCopy1Test() {
        List<String> opIds = new List<String>();
        List<Opportunity> ops = [SELECT id,Days_Aging_Range__c,Payment_Status__c,Service_Enrollment__c,STAGENAME FROM Opportunity];
        for(Opportunity op : ops){
            opIds.add(op.Id);
        }
        ApexPages.StandardSetController std = new ApexPages.StandardSetController(ops);
        BulkViewSelectorController ext = new BulkViewSelectorController(std);
        //BulkViewSelectorController.vfPageSelector(opIds,'Print and Update');
    }
    
    @isTest
    static void invoiceTemplateCopy2Test() {
        List<String> opIds = new List<String>();
        List<Opportunity> ops = [SELECT id,Days_Aging_Range__c,Payment_Status__c,Service_Enrollment__c,STAGENAME FROM Opportunity];
        for(Opportunity op : ops){
            opIds.add(op.Id);
        }
        ApexPages.StandardSetController std = new ApexPages.StandardSetController(ops);
        BulkViewSelectorController ext = new BulkViewSelectorController(std);
        BulkViewSelectorController.vfPageSelector(opIds,'Email and Update');
    }
    @isTest
    static void invoiceTemplateCopy3Test() {
        List<String> opIds = new List<String>();
        List<Opportunity> ops = [SELECT id,Days_Aging_Range__c,Payment_Status__c,Service_Enrollment__c,STAGENAME FROM Opportunity];
        for(Opportunity op : ops){
            opIds.add(op.Id);
        }
        ApexPages.StandardSetController std = new ApexPages.StandardSetController(ops);
        BulkViewSelectorController ext = new BulkViewSelectorController(std);
        BulkViewSelectorController.vfPageSelector(opIds,'Print Preview');
    }
}