force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Active Referral Source</fullName>
            </value>
            <value>
                <fullName>Inactive Referral Source</fullName>
            </value>
            <value>
                <fullName>Active Inquiry</fullName>
            </value>
            <value>
                <fullName>Inactive Inquiry</fullName>
            </value>
            <value>
                <fullName>Applicant: Active</fullName>
            </value>
            <value>
                <fullName>Applicant: Inactive</fullName>
            </value>
            <value>
                <fullName>Active Beneficiary</fullName>
            </value>
            <value>
                <fullName>Future-Funded Beneficiary</fullName>
            </value>
            <value>
                <fullName>Future-Funded Inactive</fullName>
            </value>
            <value>
                <fullName>Inactive-Deceased</fullName>
            </value>
            <value>
                <fullName>Inactive-Insufficient Funds</fullName>
            </value>
            <value>
                <fullName>Closed-Deceased</fullName>
            </value>
            <value>
                <fullName>Closed-Insufficient Funds</fullName>
            </value>
            <value>
                <fullName>Active Non-Beneficiary</fullName>
            </value>
            <value>
                <fullName>Inactive Non-Beneficiary</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <default>true</default>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Period</label>
    <referenceTo>Periods__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Service_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Service_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Enrollment</label>
    <referenceTo>Service_Enrollment__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>TEXT(Payment_Batch__r.Status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Entry_Date__c.field-meta.xml
<CustomField>
    <fullName>Entry_Date__c</fullName>
    <formula>Time_Entry__r.Entry_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Entry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Time_Entry__c.field-meta.xml
<CustomField>
    <fullName>Time_Entry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Time Entry</label>
    <referenceTo>Time_Entry__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Periods__c/Periods__c.object-meta.xml
<CustomObject>
    <label>Period</label>
    <nameField>
        <label>Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Periods__c/fields/Period_End_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_End_Date__c</fullName>
    <label>Period End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Periods__c/fields/Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_Start_Date__c</fullName>
    <label>Period Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Current_Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Current_Price_Book__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Current Price Book</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/Service_Enrollment__c.object-meta.xml
<CustomObject>
    <label>Service Enrollment</label>
    <nameField>
        <label>Service Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Enrollment__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Beneficiary</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Enrollments</relationshipLabel>
    <relationshipName>Service_Enrollments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Service_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Service_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Enrollment</label>
    <referenceTo>Service_Enrollment__c</referenceTo>
    <relationshipLabel>Service Enrollments</relationshipLabel>
    <relationshipName>Service_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Future</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Entry__c/Time_Entry__c.object-meta.xml
<CustomObject>
    <label>Time Entry</label>
    <nameField>
        <label>Time Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Entry__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beneficiary</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Date_Invoiced__c.field-meta.xml
<CustomField>
    <fullName>Date_Invoiced__c</fullName>
    <label>Date Invoiced</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Entry_Date__c.field-meta.xml
<CustomField>
    <fullName>Entry_Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Opportunity_Product__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipName>Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Period</label>
    <referenceTo>Periods__c</referenceTo>
    <relationshipName>Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <inlineHelpText>Use hour increments: 15 minutes = 0.25, 30 minutes = 0.5, 45 minutes = 0.75</inlineHelpText>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Service_Code__c.field-meta.xml
<CustomField>
    <fullName>Service_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Code</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Service_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Service_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Enrollment</label>
    <referenceTo>Service_Enrollment__c</referenceTo>
    <relationshipName>Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVE</fullName>
                <default>true</default>
                <label>ACTIVE</label>
            </value>
            <value>
                <fullName>APPROVED</fullName>
            </value>
            <value>
                <fullName>INVOICED</fullName>
            </value>
            <value>
                <fullName>CANCELED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/InvoicingBatch.cls
public class InvoicingBatch implements Database.Batchable<SObject>,Database.Stateful {
    
    Periods__c periodRec;
    Id recordTypeId;
    Id activePriceBookId;
    Map<String,Integer> statusMap = new Map<String,Integer>{'Success' => 0,'Failed' => 0};
        public InvoicingBatch(String periodId){
            this.periodRec = [Select Id,Name,Period_Start_Date__c,Period_End_Date__c from Periods__c where Id=:periodId limit 1];
            this.activePriceBookId = [Select Id,Name,IsActive from Pricebook2 where Current_Price_Book__c = true limit 1]?.Id;
            this.recordTypeId = [Select Id,Name from RecordType where Name='Client Invoice' limit 1]?.Id;
        }
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([Select ID,Entry_date__c ,Client__c, Client__r.AccountId,Description__c, Service_Enrollment__c,Service_Enrollment__r.Date_Closed__c, Service_Enrollment__r.Name,Quantity__c, Service_Code__c,Date_Invoiced__c,
                                         Unit_Price__c, Period__c, Period__r.Name, Period__r.Period_Start_Date__c,
                                         Period__r.Period_End_Date__c  from Time_Entry__c where  Status__c='APPROVED' and Service_Code__c!=null]);
    }
    public void execute(Database.BatchableContext context, List<Time_Entry__c> charges){
        try{
            Map<String,List<Time_Entry__c>> groupByData = new Map<String,List<Time_Entry__c>>();
            List<Opportunity> toCreate = new List<Opportunity>();
            List<OpportunityLineItem> oppItemToCreate = new List<OpportunityLineItem>();
            for(Time_Entry__c charge:charges){
                String key = charge.Client__c +''+ charge.Service_Enrollment__c;
                if(groupByData.containsKey(key)){
                    groupByData.get(key).add(charge);
                }else{
                    groupByData.put(key,new List<Time_Entry__c>{charge});
                }            
            }
            
            for(List<Time_Entry__c> chargesList : groupByData.values()){
                Opportunity opp = new Opportunity();
                opp.Name = chargesList[0].Service_Enrollment__r.Name + dateToString(chargesList[0].Service_Enrollment__r.Date_Closed__c);
                opp.AccountId = chargesList[0].Client__r.AccountId;
                opp.Service_Enrollment__c = chargesList[0].Service_Enrollment__c;
                opp.StageName = 'Invoiced';   
                opp.Period__c = this.periodRec.Id;
                opp.Pricebook2Id = this.activePriceBookId;
                opp.CloseDate = this.periodRec.Period_End_Date__c;
                opp.RecordTypeId = this.recordTypeId;
                toCreate.add(opp);
            }
            
            insert toCreate;
            
            Map<String, Opportunity> oppMap = new Map<String, Opportunity>();
            for(Opportunity opp : toCreate) {
                String key = opp.Service_Enrollment__c + '' + opp.AccountId;
                oppMap.put(key, opp);
            }
            system.debug('this.activePriceBookId: '+this.activePriceBookId);
            map<String,PricebookEntry> serviceCodeVsPriceBookEntry = new map<String,PricebookEntry>();
            for(PricebookEntry pe : [SELECT Id,Product2Id,Product2.Description FROM PricebookEntry WHERE Pricebook2Id = :this.activePriceBookId AND Product2Id !=null]){
                serviceCodeVsPriceBookEntry.put(pe.Product2Id,pe);
            }
            system.debug('this.serviceCodeVsPriceBookEntry: '+serviceCodeVsPriceBookEntry);
            
            map<Id,OpportunityLineItem> oppoChargeVsProdItems = new map<Id,OpportunityLineItem>();
            for(List<Time_Entry__c> chargesList : groupByData.values()){
                Opportunity opp = oppMap.get(chargesList[0].Service_Enrollment__c + '' + chargesList[0].Client__r.AccountId);
                for(Time_Entry__c charge : chargesList){
                    //charge.Status__c = 'INVOICED';
                    system.debug('Code: '+charge.Service_Code__c);
                    OpportunityLineItem item = new OpportunityLineItem();
                    item.OpportunityId = opp.Id;
                    item.Quantity = charge.Quantity__c;
                    if( String.isNotBlank(charge.Description__c))
                        item.Description = charge.Description__c;
                    else if(serviceCodeVsPriceBookEntry.containskey(charge.Service_Code__c))
                        item.Description = serviceCodeVsPriceBookEntry.get(charge.Service_Code__c).Product2.Description;
                    item.UnitPrice = charge.Unit_Price__c;
                    item.PriceBookEntryID = serviceCodeVsPriceBookEntry.size() > 0 ? serviceCodeVsPriceBookEntry.get(charge.Service_Code__c).Id : null;
                    item.ServiceDate = charge.Entry_date__c;
                    system.debug('item: '+item);
                    //oppItemToCreate.add(item);
                    oppoChargeVsProdItems.put(charge.Id,item);
                }
                //update chargesList;
            }
            insert oppoChargeVsProdItems.values();
            list<Time_Entry__c> timeEmtryToUpdate = new list<Time_Entry__c>();
            for(Id ChargeId : oppoChargeVsProdItems.keyset()){
                Time_Entry__c charge = new Time_Entry__c(Id=ChargeId);
                charge.Status__c = 'INVOICED';
                charge.Opportunity_Product__c = oppoChargeVsProdItems.get(ChargeId).Id;
                timeEmtryToUpdate.add(charge);
            }
            update timeEmtryToUpdate;
            statusMap.put('Success',statusMap.get('Success')+charges.size());
        }catch(Exception e){
            statusMap.put('Failed',statusMap.get('Failed')+charges.size());
        }
        
    }
    
    public void finish(Database.BatchableContext context){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        String[] toAddresses = new String[] {UserInfo.getUserEmail()};
            mail.setToAddresses(toAddresses);
        mail.setSubject('Invoicing batch status');
        String body = 'Batch Job Proccess is completed. \n Success: '+statusMap.get('Success') + ' \n Failed : '+statusMap.get('Failed');
        mail.setPlainTextBody(body);
        Messaging.SendEmailResult[] results = Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
    }
    
    private static String dateToString(Date toConvert){
        return '';
    }
}