force-app/main/default/objects/Contact/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
            </value>
            <value>
                <fullName>Active Referral Source</fullName>
            </value>
            <value>
                <fullName>Inactive Referral Source</fullName>
            </value>
            <value>
                <fullName>Active Inquiry</fullName>
            </value>
            <value>
                <fullName>Inactive Inquiry</fullName>
            </value>
            <value>
                <fullName>Applicant: Active</fullName>
            </value>
            <value>
                <fullName>Applicant: Inactive</fullName>
            </value>
            <value>
                <fullName>Active Beneficiary</fullName>
            </value>
            <value>
                <fullName>Future-Funded Beneficiary</fullName>
            </value>
            <value>
                <fullName>Future-Funded Inactive</fullName>
            </value>
            <value>
                <fullName>Inactive-Deceased</fullName>
            </value>
            <value>
                <fullName>Inactive-Insufficient Funds</fullName>
            </value>
            <value>
                <fullName>Closed-Deceased</fullName>
            </value>
            <value>
                <fullName>Closed-Insufficient Funds</fullName>
            </value>
            <value>
                <fullName>Active Non-Beneficiary</fullName>
            </value>
            <value>
                <fullName>Inactive Non-Beneficiary</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
                <default>true</default>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Product2/fields/Non_Billable__c.field-meta.xml
<CustomField>
    <fullName>Non_Billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Non-Billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Time_Entry_Category__c.field-meta.xml
<CustomField>
    <fullName>Time_Entry_Category__c</fullName>
    <label>Time Entry Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Entry_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/Service_Enrollment__c.object-meta.xml
<CustomObject>
    <label>Service Enrollment</label>
    <nameField>
        <label>Service Enrollment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Enrollment__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Beneficiary</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Enrollments</relationshipLabel>
    <relationshipName>Service_Enrollments</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Service_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Service_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Enrollment</label>
    <referenceTo>Service_Enrollment__c</referenceTo>
    <relationshipLabel>Service Enrollments</relationshipLabel>
    <relationshipName>Service_Enrollments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Denied</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Future</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Entry__c/Time_Entry__c.object-meta.xml
<CustomObject>
    <label>Time Entry</label>
    <nameField>
        <label>Time Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Time Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Time_Entry__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beneficiary</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Entry_Date__c.field-meta.xml
<CustomField>
    <fullName>Entry_Date__c</fullName>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Hours__c.field-meta.xml
<CustomField>
    <fullName>Hours__c</fullName>
    <label>Hours</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>4</fullName>
            </value>
            <value>
                <fullName>5</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>7</fullName>
            </value>
            <value>
                <fullName>8</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Minutes__c.field-meta.xml
<CustomField>
    <fullName>Minutes__c</fullName>
    <label>Minutes</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>6</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>18</fullName>
            </value>
            <value>
                <fullName>24</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>36</fullName>
            </value>
            <value>
                <fullName>42</fullName>
            </value>
            <value>
                <fullName>48</fullName>
            </value>
            <value>
                <fullName>54</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Non_billable__c.field-meta.xml
<CustomField>
    <fullName>Non_billable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Non-billable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <inlineHelpText>Use hour increments: 15 minutes = 0.25, 30 minutes = 0.5, 45 minutes = 0.75</inlineHelpText>
    <label>Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Service_Code__c.field-meta.xml
<CustomField>
    <fullName>Service_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Code</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Time Entries</relationshipLabel>
    <relationshipName>Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Service_Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Service_Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Enrollment</label>
    <referenceTo>Service_Enrollment__c</referenceTo>
    <relationshipName>Charges</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVE</fullName>
                <default>true</default>
                <label>ACTIVE</label>
            </value>
            <value>
                <fullName>APPROVED</fullName>
            </value>
            <value>
                <fullName>INVOICED</fullName>
            </value>
            <value>
                <fullName>CANCELED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Time_Entry__c/fields/Time_Entry_Category__c.field-meta.xml
<CustomField>
    <fullName>Time_Entry_Category__c</fullName>
    <label>Time Entry Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Entry_Category</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Time_Entry_Category.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>HOURLY SERVICE</fullName>
        <default>true</default>
        <label>HOURLY SERVICE</label>
    </customValue>
    <customValue>
        <fullName>ADMINISTRATIVE TIME</fullName>
    </customValue>
    <customValue>
        <fullName>DIRECT EXPENSE</fullName>
    </customValue>
    <customValue>
        <fullName>FEES</fullName>
    </customValue>
    <customValue>
        <fullName>Time</fullName>
        <isActive>false</isActive>
        <label>Time</label>
    </customValue>
    <customValue>
        <fullName>Expense</fullName>
        <isActive>false</isActive>
        <label>Expense</label>
    </customValue>
    <masterLabel>Time Entry Category</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/BulkTimeEntryUtils.cls
/**
* @File Name : BulkTimeEntryUtilsWithApproval.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : November 17, 2024
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | November 17, 2024 |   | Initial Version
**/

public class BulkTimeEntryUtils {
	@AuraEnabled(cacheable=true)
    public static List<Contact> getClients(){
        return [Select Id,Name from Contact where Id IN (Select Client__c from Service_Enrollment__c WHERE Status__c IN ('Enrolled','Closing','Pending')) order by Name];
    }

    @AuraEnabled(cacheable=true)
    public static List<Service_Enrollment__c> getServiceEntollment(String clientId){
        return [Select Id,Name from Service_Enrollment__c where Client__C =:clientId AND Status__c IN ('Enrolled','Closing','Pending')];
    }

    @AuraEnabled(cacheable=true)
    public static List<Product2> getBillingCode(String category){
        return [Select Id,Name from Product2 where Time_Entry_Category__c =: category AND IsActive = true];
    }

    @AuraEnabled(cacheable=true)
    public static Double getUnitPrice(String billingCode){
        return [Select Id,UnitPrice from PricebookEntry where Product2Id =:billingCode and PriceBook2Id IN (Select Id from Pricebook2 where IsActive = true)]?.UnitPrice;
    }

    @AuraEnabled
    public static List<Time_Entry__c> getCharges(String periodSearch){
        if(periodSearch == 'THIS_WEEK')
            return [Select Id,Name,CreatedBy.Name,Client__r.FirstName,Time_Entry_Category__c,Hours__c,Minutes__c,Quantity__c,Non_billable__c,Client__r.LastName,Service_Enrollment__r.Name,Description__c,Entry_date__c,Service_Code__r.Name,Unit_Price__c,Status__c,Approved__c from Time_Entry__c where Entry_date__c = THIS_WEEK order by createddate desc];
        if(periodSearch == 'THIS_MONTH')
            return [Select Id,Name,CreatedBy.Name,Client__r.FirstName,Time_Entry_Category__c,Hours__c,Minutes__c,Quantity__c,Non_billable__c,Client__r.LastName,Service_Enrollment__r.Name,Description__c,Entry_date__c,Service_Code__r.Name,Unit_Price__c,Status__c,Approved__c from Time_Entry__c where Entry_date__c = THIS_MONTH order by createddate desc];
        if(periodSearch == 'TODAY')
            return [Select Id,Name,CreatedBy.Name,Client__r.FirstName,Time_Entry_Category__c,Hours__c,Minutes__c,Quantity__c,Non_billable__c,Client__r.LastName,Service_Enrollment__r.Name,Description__c,Entry_date__c,Service_Code__r.Name,Unit_Price__c,Status__c,Approved__c from Time_Entry__c where Entry_date__c = TODAY order by createddate desc];
        if(periodSearch == 'LAST_MONTH')
            return [Select Id,Name,CreatedBy.Name,Client__r.FirstName,Time_Entry_Category__c,Hours__c,Minutes__c,Quantity__c,Non_billable__c,Client__r.LastName,Service_Enrollment__r.Name,Description__c,Entry_date__c,Service_Code__r.Name,Unit_Price__c,Status__c,Approved__c from Time_Entry__c where Entry_date__c = LAST_MONTH order by createddate desc];
        return new List<Time_Entry__c>();
    }
}