force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Beneficiary__c.field-meta.xml
<CustomField>
    <fullName>Beneficiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beneficiary</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Merchant_Name__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Name__c</fullName>
    <label>Merchant Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Payee_City__c.field-meta.xml
<CustomField>
    <fullName>Payee_City__c</fullName>
    <label>Payee City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Payee_Description__c.field-meta.xml
<CustomField>
    <fullName>Payee_Description__c</fullName>
    <label>Payee Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Payee_Name__c.field-meta.xml
<CustomField>
    <fullName>Payee_Name__c</fullName>
    <label>Payee Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Payee_State__c.field-meta.xml
<CustomField>
    <fullName>Payee_State__c</fullName>
    <label>Payee State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Payee_Street_1__c.field-meta.xml
<CustomField>
    <fullName>Payee_Street_1__c</fullName>
    <label>Payee Street 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Payee_Street_2__c.field-meta.xml
<CustomField>
    <fullName>Payee_Street_2__c</fullName>
    <label>Payee Street 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Payee_Zip__c.field-meta.xml
<CustomField>
    <fullName>Payee_Zip__c</fullName>
    <label>Payee Zip</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/summaryTemplateController.cls
public class summaryTemplateController {
    public list<Transaction__c> tranxList {get;set;}
    public Boolean noLetterHead {get;set;}
    public summaryTemplateController(){
        tranxList = new list<Transaction__c>();
        noLetterHead = ApexPages.currentPage().getParameters().get('noLetterHead')!=null ? 
            Boolean.valueof(ApexPages.currentPage().getParameters().get('noLetterHead')) : false;
        String param = ApexPages.currentPage().getParameters().get('bulkIds');
        list<Id> paramIds = new list<Id>();
        if(String.isNotBlank(param) && param.contains(',')){
            paramIds.addALL(param.split(','));
        } else {
            paramIds.add(param);
        }
        if(!paramIds.isEmpty()){
            String query= 'select Name,Payee_Street_1__c,Payee_Street_2__c,Payee_State__c,Payee_Name__c,Payee_City__c,Payee_Zip__c,Amount__c,'+
             		'Cleared_Date__c,Merchant_Name__c,Payee_Description__c, Beneficiary__r.Email';
                    for(Schema.FieldSetMember fld :SObjectType.Transaction__c.FieldSets.Bulk_Print_and_Email.getFields()) {
                        if(!query.contains(fld.getFieldPath())){
                            query += ', ' + fld.getFieldPath();
                        }
                    }

             query += ' from Transaction__c where id IN :paramIds';
             tranxList = Database.query(query);
        }
    }
}