force-app/main/default/objects/Periods__c/Periods__c.object-meta.xml
<CustomObject>
    <label>Period</label>
    <nameField>
        <label>Period Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Periods</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Periods__c/fields/Is_Closed__c.field-meta.xml
<CustomField>
    <fullName>Is_Closed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Closed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Periods__c/fields/Period_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Period_Start_Date__c</fullName>
    <label>Period Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/User/fields/Can_Create_Invoices__c.field-meta.xml
<CustomField>
    <fullName>Can_Create_Invoices__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Can Create Invoices</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/InvoicingBatchUtil.cls
public class InvoicingBatchUtil {
    @AuraEnabled
    public static Boolean checkAccess(){
        String userId = UserInfo.getUserId();
        return [Select Id,Can_Create_Invoices__c from User where Id=:userId limit 1].Can_Create_Invoices__c;
    }

    @AuraEnabled(cacheable=true)
    public static List<Periods__c> getPeriodValues(){
        List<String> toRet = new List<String>();
        for(Periods__c pr:[Select ID, Name from Periods__c where Is_Closed__c=False Order By Period_Start_Date__c ASC Limit 4]){
            toRet.add(pr.Name);
        }
//        return toRet;
        return [Select ID, Name from Periods__c where Is_Closed__c=False Order By Period_Start_Date__c ASC Limit 4];
    }
    
    @AuraEnabled
    public static void runBatch(String periodId){
        Database.executeBatch(new InvoicingBatch(periodId));
    }
}