force-app/main/default/objects/Docsumo_Config__mdt/Docsumo_Config__mdt.object-meta.xml
<CustomObject>
    <label>Docsumo Config</label>
    <pluralLabel>Docsumo Configs</pluralLabel>
</CustomObject>

force-app/main/default/objects/Docsumo_Config__mdt/fields/api_key__c.field-meta.xml
<CustomField>
    <fullName>api_key__c</fullName>
    <label>api key</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Docsumo_Config__mdt/fields/base_url__c.field-meta.xml
<CustomField>
    <fullName>base_url__c</fullName>
    <label>Base URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/DocsumoBSAnalytics.cls
public with sharing class DocsumoBSAnalytics {
  public static final Docsumo_Config__mdt configMetadata = [
          SELECT label, base_url__c, api_key__c
          FROM Docsumo_Config__mdt
          LIMIT 1
  ];
  @AuraEnabled
  public static String getBSAnalytics(String docId) {
    String url =
      configMetadata.base_url__c + '/api/v1/mew/usbs-analytics/' +
      docId +
      '/?date_format=mmddyy&mode=full';

    Integer maxRetries = 5;
    for (Integer i = 0; i < maxRetries; i++) {
      try {
        System.debug('fetching analytics. Call:' + 1);
        return DocsumoAPIUtils.fetchApi(url);
      } catch (CalloutException e) {
        System.debug('Callout exception: ' + e.getMessage());
      }
    }

    return null;
  }
}