force-app/main/default/objects/Truelink_Feature_Management__c/Truelink_Feature_Management__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Truelink Feature Management</label>
</CustomObject>

force-app/main/default/objects/Truelink_Feature_Management__c/fields/Deposit_Last_Run_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Deposit_Last_Run_Datetime__c</fullName>
    <label>Deposit Last Run Datetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trust__c/Trust__c.object-meta.xml
<CustomObject>
    <description>Record the history of trust agreements for a beneficiary</description>
    <label>Trust</label>
    <nameField>
        <label>Trust ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trusts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trust__c/fields/True_Link_Balance__c.field-meta.xml
<CustomField>
    <fullName>True_Link_Balance__c</fullName>
    <label>TrueLink Balance</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trust__c/fields/TrueLink_ID__c.field-meta.xml
<CustomField>
    <fullName>TrueLink_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>TrueLink ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/UpdateDepositsBatch.cls
public class UpdateDepositsBatch implements Database.Batchable<sObject>,Database.AllowsCallouts {
    public Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator([Select Id,TrueLink_ID__c,True_Link_Balance__c from trust__c where TrueLink_ID__c!=null]);
    }

    public void execute(Database.BatchableContext ctx,List<trust__c> records){   
        List<trust__c> newRecords = new List<trust__c>();
        for(trust__c trust:records){
            TrueLinkApiHandler.updateDeposit(trust.Id);
        }
    }

    public void finish(Database.BatchableContext ctx){
        Truelink_Feature_Management__c feature = Truelink_Feature_Management__c.getOrgDefaults();
        feature.Deposit_Last_Run_Datetime__c = system.now();
        if(!Test.isRunningTest())
        	update feature;
        
        Database.executeBatch(new UpdateDisbursementsBatch(),1);

    }
}