force-app/main/default/objects/Contact/recordTypes/Contact.recordType-meta.xml
<RecordType>
    <fullName>Contact</fullName>
    <active>true</active>
    <label>Contact</label>
</RecordType>

force-app/main/default/objects/Pooled_Trust__c/Pooled_Trust__c.object-meta.xml
<CustomObject>
    <label>Pooled Trust</label>
    <nameField>
        <label>Pooled Trust Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pooled Trusts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pooled_Trust__c/fields/Trust_ID__c.field-meta.xml
<CustomField>
    <fullName>Trust_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Trust ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <label>Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Beneficiary__c.field-meta.xml
<CustomField>
    <fullName>Beneficiary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Beneficiary</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Merchant_Name__c.field-meta.xml
<CustomField>
    <fullName>Merchant_Name__c</fullName>
    <label>Merchant Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Payee_Description__c.field-meta.xml
<CustomField>
    <fullName>Payee_Description__c</fullName>
    <label>Payee Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Trust__c.field-meta.xml
<CustomField>
    <fullName>Trust__c</fullName>
    <label>Trust</label>
    <referenceTo>Trust__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Deposit</fullName>
            </value>
            <value>
                <fullName>Disbursement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trust__c/Trust__c.object-meta.xml
<CustomObject>
    <description>Record the history of trust agreements for a beneficiary</description>
    <label>Trust</label>
    <nameField>
        <label>Trust ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trusts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trust__c/fields/Beneficiary__c.field-meta.xml
<CustomField>
    <fullName>Beneficiary__c</fullName>
    <label>Beneficiary</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Trusts</relationshipLabel>
    <relationshipName>Trusts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trust__c/fields/Pooled_Trust__c.field-meta.xml
<CustomField>
    <fullName>Pooled_Trust__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pooled Trust</label>
    <referenceTo>Pooled_Trust__c</referenceTo>
    <relationshipLabel>Trusts</relationshipLabel>
    <relationshipName>Trusts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trust__c/fields/TrueLink_ID__c.field-meta.xml
<CustomField>
    <fullName>TrueLink_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>TrueLink ID</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Trust__c/fields/Trust_Portfolio__c.field-meta.xml
<CustomField>
    <fullName>Trust_Portfolio__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Trust Portfolio</label>
    <referenceTo>Trust_Portfolio__c</referenceTo>
    <relationshipLabel>Trusts</relationshipLabel>
    <relationshipName>Trusts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trust__c/fields/Trust_Status__c.field-meta.xml
<CustomField>
    <fullName>Trust_Status__c</fullName>
    <label>Trust Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Intake</fullName>
                <default>true</default>
                <label>Intake</label>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Future Funded</fullName>
            </value>
            <value>
                <fullName>Closing</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active-Pending</fullName>
                <isActive>false</isActive>
                <label>Active-Pending</label>
            </value>
            <value>
                <fullName>Closing requested</fullName>
                <isActive>false</isActive>
                <label>Closing requested</label>
            </value>
            <value>
                <fullName>Materials Received-Complete</fullName>
                <isActive>false</isActive>
                <label>Materials Received-Complete</label>
            </value>
            <value>
                <fullName>Pending-Active</fullName>
                <isActive>false</isActive>
                <label>Pending-Active</label>
            </value>
            <value>
                <fullName>Pending-Inactive</fullName>
                <isActive>false</isActive>
                <label>Pending-Inactive</label>
            </value>
            <value>
                <fullName>Received</fullName>
                <isActive>false</isActive>
                <label>Received</label>
            </value>
            <value>
                <fullName>Returning</fullName>
                <isActive>false</isActive>
                <label>Returning</label>
            </value>
            <value>
                <fullName>Reviewed</fullName>
                <isActive>false</isActive>
                <label>Reviewed</label>
            </value>
            <value>
                <fullName>Waiting/Hold</fullName>
                <isActive>false</isActive>
                <label>Waiting/Hold</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trust_Portfolio__c/Trust_Portfolio__c.object-meta.xml
<CustomObject>
    <label>Trust Portfolio</label>
    <nameField>
        <label>Trust Portfolio Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trust Portfolios</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trust_Portfolio__c/fields/Pooled_Trust__c.field-meta.xml
<CustomField>
    <fullName>Pooled_Trust__c</fullName>
    <label>Pooled Trust</label>
    <referenceTo>Pooled_Trust__c</referenceTo>
    <relationshipLabel>Trust Portfolios</relationshipLabel>
    <relationshipName>Trust_Portfolios</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trust_Portfolio__c/fields/True_Link_Portfolio_ID__c.field-meta.xml
<CustomField>
    <fullName>True_Link_Portfolio_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>TrueLink Portfolio ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Trust_Portfolio__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Portfolio</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/summaryTemplateControllerTest.cls
@isTest
public class summaryTemplateControllerTest {
	@isTest
    static void testController() {
        // Step 1: Create test data
        Pooled_Trust__c pc = new Pooled_Trust__c(Trust_Id__c = 'AB123');
        insert pc;
        
        Trust_Portfolio__c tp = new Trust_Portfolio__c (name='test', Is_Default__c=true, True_Link_Portfolio_ID__c='test', Type__c='Portfolio', Pooled_Trust__c=pc.id);
        insert tp;
        
        contact con = new contact(lastname='Account VALUE NEW' );
        insert con;
        
        trust__c trust = new trust__c(Name='Test Trust Account', beneficiary__c=con.id, Trust_Portfolio__c=tp.id, Pooled_Trust__c=pc.id, TrueLink_Id__c='TestTrustId', Trust_Status__c='Inactive');
        insert trust;
        
        Account acc = new Account(Name = 'Test Account', BillingStreet = '123 Test St', BillingCity = 'Test City', BillingState = 'Test State');
        insert acc;

        Contact contact = new Contact(LastName = 'Test Contact', AccountId = acc.Id);
        insert contact;

        transaction__c opp = new transaction__c(
            Name = 'Test Opportunity',
            Amount__c = 1000,
            Merchant_Name__c  = 'test',
            Payee_Description__c = 'Test Opportunity Description',
            Cleared_Date__c = Date.today().addDays(10),
            Trust__c = trust.id
        );
        insert opp;

        // Step 2: Set the ApexPages parameters
        Test.startTest();
        ApexPages.currentPage().getParameters().put('bulkIds', opp.Id);

        // Step 3: Instantiate the controller
        summaryTemplateController controller = new summaryTemplateController();
        Test.stopTest();
    }
}